package com.efit.hrms.repo;

import java.util.List;
import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.efit.hrms.entity.AttendanceDailyVO;
import com.efit.hrms.entity.AttendanceSummaryVO;

@Repository
public interface AttendanceSummaryRepo extends JpaRepository<AttendanceSummaryVO, Long>{

	@Query(nativeQuery = true, value = 
		    "SELECT * " +
		    "FROM attendancesummary a " +
		    "WHERE a.orgid = ?1 " +
		    "AND (?2 = 'All' OR a.branch = ?2) " +
		    "AND a.approvestatus = 'PENDING'"
		)
	List<AttendanceSummaryVO> getPendingAttendanceSummaryByOrgId( Long orgId,
			String branch);

	@Query(nativeQuery = true, value = " SELECT * FROM attendancesummary a\r\n"
			+ "    WHERE (?1 = 'ALL' OR a.empcode = ?1)"
			+ "     AND (?2 IS NULL OR a.month = ?2)\r\n"
			+ "      AND (?3 IS NULL OR a.finyear = ?3)\r\n"
			+ "      AND a.orgid = ?4\r\n"
			+ "      AND (?5 = 'ALL' OR UPPER(a.branch) = UPPER(?5))\r\n"
			+ "      AND a.approvestatus = 'APPROVED'")   
	List<AttendanceSummaryVO> getAttendanceSummaryByOrgId(String empCode,Integer month,String finYear,Long orgId, String branch);

//	@Query(nativeQuery = true, value = 
//		    "WITH RECURSIVE separation_data AS (\r\n"
//		    + "    SELECT \r\n"
//		    + "        s.employeecode,\r\n"
//		    + "        s.resignation,\r\n"
//		    + "        s.lastworkingdate,\r\n"
//		    + "        DATE_FORMAT(s.resignation,'%Y-%m-01') AS startdate\r\n"
//		    + "    FROM initiateseparation s\r\n"
//		    + "    WHERE s.status = 'APPROVED'\r\n"
//		    + "      AND s.orgid = ?1\r\n"
//		    + "      AND (?2 = 'ALL' OR s.employeecode = ?2)\r\n"
//		    + "),\r\n"
//		    + "\r\n"
//		    + "date_series AS (\r\n"
//		    + "    SELECT employeecode, startdate AS dt, lastworkingdate\r\n"
//		    + "    FROM separation_data\r\n"
//		    + "    UNION ALL\r\n"
//		    + "    SELECT employeecode, DATE_ADD(dt, INTERVAL 1 DAY), lastworkingdate\r\n"
//		    + "    FROM date_series\r\n"
//		    + "    WHERE dt < lastworkingdate\r\n"
//		    + "),\r\n"
//		    + "\r\n"
//		    + "emp_base AS (\r\n"
//		    + "    SELECT * FROM employee WHERE orgid = ?1 AND (?3 = 'ALL' OR branchcode = ?3)\r\n"
//		    + "),\r\n"
//		    + "\r\n"
//		    + "-- 🔹 ATTENDANCE\r\n"
//		    + "att_data AS (\r\n"
//		    + "    SELECT \r\n"
//		    + "        a.empcode,\r\n"
//		    + "        a.checkindate,\r\n"
//		    + "        CASE \r\n"
//		    + "            WHEN SUM(a.effectivehours) >= MAX(sm.fulldayhours) THEN 1\r\n"
//		    + "            WHEN SUM(a.effectivehours) >= MAX(sm.halfdayhours) THEN 0.5\r\n"
//		    + "            ELSE 0\r\n"
//		    + "        END AS present_value\r\n"
//		    + "    FROM attendancedaily a\r\n"
//		    + "    JOIN shiftassigndetails sd \r\n"
//		    + "        ON a.empcode = sd.employeecode\r\n"
//		    + "       AND a.checkindate BETWEEN sd.effectivefrom AND sd.effectiveto\r\n"
//		    + "    JOIN shiftmaster sm ON sm.shiftcode = sd.shiftcode\r\n"
//		    + "    GROUP BY a.empcode, a.checkindate\r\n"
//		    + "),\r\n"
//		    + "\r\n"
//		    + "-- 🔹 PRESENT BEFORE RESIGN\r\n"
//		    + "res_present_days AS (\r\n"
//		    + "    SELECT \r\n"
//		    + "        a.empcode,\r\n"
//		    + "        SUM(a.present_value) AS presentdays\r\n"
//		    + "    FROM att_data a\r\n"
//		    + "    JOIN separation_data sd ON sd.employeecode = a.empcode\r\n"
//		    + "    WHERE a.checkindate BETWEEN \r\n"
//		    + "        DATE_FORMAT(sd.resignation,'%Y-%m-01')\r\n"
//		    + "        AND DATE_SUB(sd.resignation, INTERVAL 1 DAY)\r\n"
//		    + "    GROUP BY a.empcode\r\n"
//		    + "),\r\n"
//		    + "\r\n"
//		    + "-- 🔹 WEEKOFF\r\n"
//		    + "weekoffs AS (\r\n"
//		    + "    SELECT DISTINCT ds.dt AS weekoffdate, eb.employeecode\r\n"
//		    + "    FROM date_series ds\r\n"
//		    + "    JOIN emp_base eb ON eb.weekoffeligible = 1\r\n"
//		    + "    JOIN companyweekoff cw\r\n"
//		    + "        ON cw.companyid = ?1\r\n"
//		    + "       AND UPPER(DAYNAME(ds.dt)) = UPPER(cw.weekoffdays)\r\n"
//		    + "    JOIN weekoffoccurrences wo\r\n"
//		    + "        ON wo.companyweekoffid = cw.companyweekoffid\r\n"
//		    + "    WHERE wo.weeknumber = -1\r\n"
//		    + "       OR wo.weeknumber = (1 + FLOOR((DAY(ds.dt) - 1) / 7))\r\n"
//		    + "),\r\n"
//		    + "\r\n"
//		    + "weekoff_res AS (\r\n"
//		    + "    SELECT w.employeecode, COUNT(*) AS weekoff_res\r\n"
//		    + "    FROM weekoffs w\r\n"
//		    + "    JOIN separation_data sd ON sd.employeecode = w.employeecode\r\n"
//		    + "    LEFT JOIN attendancedaily a\r\n"
//		    + "        ON a.empcode = w.employeecode\r\n"
//		    + "       AND a.checkindate = w.weekoffdate\r\n"
//		    + "    WHERE w.weekoffdate BETWEEN \r\n"
//		    + "        DATE_FORMAT(sd.resignation,'%Y-%m-01')\r\n"
//		    + "        AND DATE_SUB(sd.resignation, INTERVAL 1 DAY)\r\n"
//		    + "      AND a.empcode IS NULL\r\n"
//		    + "    GROUP BY w.employeecode\r\n"
//		    + "),\r\n"
//		    + "\r\n"
//		    + "-- 🔹 HOLIDAY\r\n"
//		    + "holidays_cte AS (\r\n"
//		    + "    SELECT h.holidaydate, eb.employeecode\r\n"
//		    + "    FROM holidays h\r\n"
//		    + "    JOIN emp_base eb ON 1=1\r\n"
//		    + "    LEFT JOIN attendancedaily a\r\n"
//		    + "        ON a.empcode = eb.employeecode\r\n"
//		    + "       AND a.checkindate = h.holidaydate\r\n"
//		    + "    WHERE h.orgid = ?1\r\n"
//		    + "      AND a.empcode IS NULL\r\n"
//		    + "),\r\n"
//		    + "\r\n"
//		    + "holiday_res AS (\r\n"
//		    + "    SELECT h.employeecode, COUNT(*) AS holidays_res\r\n"
//		    + "    FROM holidays_cte h\r\n"
//		    + "    JOIN separation_data sd ON sd.employeecode = h.employeecode\r\n"
//		    + "    WHERE h.holidaydate BETWEEN \r\n"
//		    + "        DATE_FORMAT(sd.resignation,'%Y-%m-01')\r\n"
//		    + "        AND sd.resignation\r\n"
//		    + "    GROUP BY h.employeecode\r\n"
//		    + "),\r\n"
//		    + "\r\n"
//		    + "-- 🔹 LEAVE\r\n"
//		    + "res_leave_days AS (\r\n"
//		    + "    SELECT l.employeecode, SUM(l.totalleave) AS leaves\r\n"
//		    + "    FROM approvalleaves l\r\n"
//		    + "    JOIN separation_data sd ON sd.employeecode = l.employeecode\r\n"
//		    + "    WHERE l.leavetype != 'LOSS OF PAY'\r\n"
//		    + "      AND l.leavedate BETWEEN \r\n"
//		    + "        DATE_FORMAT(sd.resignation,'%Y-%m-01')\r\n"
//		    + "        AND sd.resignation\r\n"
//		    + "    GROUP BY l.employeecode\r\n"
//		    + "),\r\n"
//		    + "\r\n"
//		    + "-- 🔹 LOP\r\n"
//		    + "lop_res AS (\r\n"
//		    + "    SELECT l.employeecode, SUM(l.totalleave) AS lop\r\n"
//		    + "    FROM approvalleaves l\r\n"
//		    + "    JOIN separation_data sd ON sd.employeecode = l.employeecode\r\n"
//		    + "    WHERE l.leavetype = 'LOSS OF PAY'\r\n"
//		    + "      AND l.leavedate BETWEEN \r\n"
//		    + "        DATE_FORMAT(sd.resignation,'%Y-%m-01')\r\n"
//		    + "        AND sd.resignation\r\n"
//		    + "    GROUP BY l.employeecode\r\n"
//		    + "),\r\n"
//		    + "\r\n"
//		    + "salary_info AS (\r\n"
//		    + "    SELECT employeecode, sumofearning, sumofdetection\r\n"
//		    + "    FROM salarystructure\r\n"
//		    + "),\r\n"
//		    + "\r\n"
//		    + "-- 🔹 BASE\r\n"
//		    + "base AS (\r\n"
//		    + "    SELECT\r\n"
//		    + "        eb.employeecode,\r\n"
//		    + "        eb.employee,\r\n"
//		    + "        sd.resignation,\r\n"
//		    + "        sd.lastworkingdate,\r\n"
//		    + "\r\n"
//		    + "        ROUND(\r\n"
//		    + "        (\r\n"
//		    + "            (\r\n"
//		    + "                COALESCE(rp.presentdays, 0)\r\n"
//		    + "              + COALESCE(wr.weekoff_res, 0)\r\n"
//		    + "              + COALESCE(hr.holidays_res, 0)\r\n"
//		    + "              + COALESCE(rl.leaves, 0)\r\n"
//		    + "              - COALESCE(lp.lop, 0)\r\n"
//		    + "            )\r\n"
//		    + "            +\r\n"
//		    + "            DATEDIFF(\r\n"
//		    + "                LAST_DAY(sd.resignation),\r\n"
//		    + "                DATE_SUB(sd.resignation, INTERVAL 1 DAY)\r\n"
//		    + "            )\r\n"
//		    + "        ),1) AS res_month_working_days,\r\n"
//		    + "\r\n"
//		    + "        DAY(LAST_DAY(sd.resignation)) AS res_month_days,\r\n"
//		    + "\r\n"
//		    + "        DAY(LAST_DAY(sd.lastworkingdate)) AS next_month_days,\r\n"
//		    + "\r\n"
//		    + "        DATEDIFF(\r\n"
//		    + "            sd.lastworkingdate,\r\n"
//		    + "            DATE_FORMAT(sd.lastworkingdate,'%Y-%m-01')\r\n"
//		    + "        ) + 1 AS next_month_worked_days,\r\n"
//		    + "\r\n"
//		    + "        si.sumofearning,\r\n"
//		    + "        si.sumofdetection\r\n"
//		    + "\r\n"
//		    + "    FROM separation_data sd\r\n"
//		    + "    JOIN emp_base eb ON eb.employeecode = sd.employeecode\r\n"
//		    + "    LEFT JOIN res_present_days rp ON rp.empcode = eb.employeecode\r\n"
//		    + "    LEFT JOIN weekoff_res wr ON wr.employeecode = eb.employeecode\r\n"
//		    + "    LEFT JOIN holiday_res hr ON hr.employeecode = eb.employeecode\r\n"
//		    + "    LEFT JOIN res_leave_days rl ON rl.employeecode = eb.employeecode\r\n"
//		    + "    LEFT JOIN lop_res lp ON lp.employeecode = eb.employeecode\r\n"
//		    + "    LEFT JOIN salary_info si ON si.employeecode = eb.employeecode\r\n"
//		    + "),\r\n"
//		    + "\r\n"
//		    + "-- 🔹 MONTH LOOP\r\n"
//		    + "months AS (\r\n"
//		    + "    SELECT \r\n"
//		    + "        employeecode, employee,\r\n"
//		    + "        DATE_FORMAT(resignation,'%Y-%m-01') AS mth,\r\n"
//		    + "        resignation, lastworkingdate,\r\n"
//		    + "        res_month_working_days, res_month_days,\r\n"
//		    + "        next_month_worked_days, next_month_days,\r\n"
//		    + "        sumofearning, sumofdetection\r\n"
//		    + "    FROM base\r\n"
//		    + "\r\n"
//		    + "    UNION ALL\r\n"
//		    + "\r\n"
//		    + "    SELECT \r\n"
//		    + "        employeecode, employee,\r\n"
//		    + "        DATE_ADD(mth, INTERVAL 1 MONTH),\r\n"
//		    + "        resignation, lastworkingdate,\r\n"
//		    + "        res_month_working_days, res_month_days,\r\n"
//		    + "        next_month_worked_days, next_month_days,\r\n"
//		    + "        sumofearning, sumofdetection\r\n"
//		    + "    FROM months\r\n"
//		    + "    WHERE mth < DATE_FORMAT(lastworkingdate,'%Y-%m-01')\r\n"
//		    + "),\r\n"
//		    + "\r\n"
//		    + "-- 🔹 FINAL\r\n"
//		    + "final AS (\r\n"
//		    + "    SELECT \r\n"
//		    + "        employeecode,\r\n"
//		    + "        employee,\r\n"
//		    + "        resignation,\r\n"
//		    + "        lastworkingdate,\r\n"
//		    + "        DATE_FORMAT(mth,'%b-%Y') AS month,\r\n"
//		    + "\r\n"
//		    + "        CASE \r\n"
//		    + "            WHEN DATE_FORMAT(mth,'%Y-%m') = DATE_FORMAT(resignation,'%Y-%m')\r\n"
//		    + "                THEN res_month_working_days\r\n"
//		    + "            WHEN DATE_FORMAT(mth,'%Y-%m') = DATE_FORMAT(lastworkingdate,'%Y-%m')\r\n"
//		    + "                THEN next_month_worked_days\r\n"
//		    + "            ELSE DAY(LAST_DAY(mth))\r\n"
//		    + "        END AS payable_days,\r\n"
//		    + "\r\n"
//		    + "        CASE \r\n"
//		    + "            WHEN DATE_FORMAT(mth,'%Y-%m') = DATE_FORMAT(resignation,'%Y-%m')\r\n"
//		    + "                THEN res_month_days\r\n"
//		    + "            ELSE DAY(LAST_DAY(mth))\r\n"
//		    + "        END AS total_days,\r\n"
//		    + "\r\n"
//		    + "        sumofearning,\r\n"
//		    + "        sumofdetection\r\n"
//		    + "    FROM months\r\n"
//		    + ")\r\n"
//		    + "\r\n"
//		    + "-- 🔹 FINAL OUTPUT\r\n"
//		    + "SELECT \r\n"
//		    + "    employeecode,\r\n"
//		    + "    employee,\r\n"
//		    + "    resignation,\r\n"
//		    + "    lastworkingdate,\r\n"
//		    + "  DATE_ADD(\r\n"
//		    + "    lastworkingdate,\r\n"
//		    + "    INTERVAL CEIL(COALESCE((\r\n"
//		    + "        SELECT SUM(l.totalleave)\r\n"
//		    + "        FROM approvalleaves l\r\n"
//		    + "        WHERE l.employeecode = final.employeecode AND l.leavetype = 'LOSS OF PAY' \r\n"
//		    + "          AND l.leavedate BETWEEN final.resignation AND final.lastworkingdate\r\n"
//		    + "    ),0)) DAY\r\n"
//		    + ") AS finalworkingdate,\r\n"
//		    + "    month,\r\n"
//		    + "    total_days AS month_total_days, \r\n"
//		    + "    payable_days,\r\n"
//		    + "    sumofearning,\r\n"
//		    + "    sumofdetection,\r\n"
//		    + "    ROUND(sumofearning / total_days,2) AS per_day_salary,\r\n"
//		    + "    ROUND((sumofearning / total_days) * payable_days,2) AS gross_salary,\r\n"
//		    + "    ROUND(\r\n"
//		    + "        ((sumofearning / total_days) * payable_days)\r\n"
//		    + "        -\r\n"
//		    + "        ((sumofdetection / total_days) * payable_days)\r\n"
//		    + "    ,2) AS net_salary\r\n"
//		    + "FROM final\r\n"
//		    + "\r\n"
//		    + "UNION ALL\r\n"
//		    + "\r\n"
//		    + "-- 🔥 TOTAL\r\n"
//		    + "SELECT \r\n"
//		    + "    'TOTAL',\r\n"
//		    + "    '',\r\n"
//		    + "    NULL,\r\n"
//		    + "    NULL,\r\n"
//		    + "    NULL,\r\n"
//		    + "    '',\r\n"
//		    + "    NULL,\r\n"
//		    + "    ROUND(SUM(payable_days),1),\r\n"
//		    + "    NULL,\r\n"
//		    + "    NULL,\r\n"
//		    + "    NULL,\r\n"
//		    + "    ROUND(SUM(gross_salary),2),\r\n"
//		    + "    ROUND(SUM(net_salary),2)\r\n"
//		    + "FROM (\r\n"
//		    + "    SELECT \r\n"
//		    + "        payable_days,\r\n"
//		    + "        (sumofearning / total_days) * payable_days AS gross_salary,\r\n"
//		    + "        ((sumofearning / total_days) * payable_days)\r\n"
//		    + "        -\r\n"
//		    + "        ((sumofdetection / total_days) * payable_days) AS net_salary\r\n"
//		    + "    FROM final\r\n"
//		    + ") t\r\n"
//		    + "\r\n"
//		    + "ORDER BY \r\n"
//		    + "    CASE WHEN employeecode='TOTAL' THEN 1 ELSE 0 END,\r\n"
//		    + "    STR_TO_DATE(month,'%b-%Y')"
//		)
//	Set<Object[]> getpayslipSettlementDetails(Long orgId, String empCode,String branchCode);
	
	
	@Query(nativeQuery = true, value = 
		    "WITH RECURSIVE separation_data AS (\r\n"
		    + "    SELECT \r\n"
		    + "        s.employeecode,\r\n"
		    + "        s.resignation,\r\n"
		    + "        s.lastworkingdate,\r\n"
		    + "        DATE_FORMAT(s.resignation,'%Y-%m-01') AS startdate\r\n"
		    + "    FROM initiateseparation s\r\n"
		    + "    WHERE s.status = 'APPROVED'\r\n"
		    + "      AND s.orgid = ?1\r\n"
		    + "      AND (?2 = 'ALL' OR s.employeecode = ?2)\r\n"
		    + "),\r\n"
		    + "\r\n"
		    + "date_series AS (\r\n"
		    + "    SELECT employeecode, startdate AS dt, lastworkingdate\r\n"
		    + "    FROM separation_data\r\n"
		    + "    UNION ALL\r\n"
		    + "    SELECT employeecode, DATE_ADD(dt, INTERVAL 1 DAY), lastworkingdate\r\n"
		    + "    FROM date_series\r\n"
		    + "    WHERE dt < lastworkingdate\r\n"
		    + "),\r\n"
		    + "\r\n"
		    + "emp_base AS (\r\n"
		    + "    SELECT * \r\n"
		    + "    FROM employee \r\n"
		    + "    WHERE orgid = ?1 \r\n"
		    + "      AND (?3 = 'ALL' OR branchcode = ?3)\r\n"
		    + "),\r\n"
		    + "\r\n"
		    + "att_data AS (\r\n"
		    + "    SELECT \r\n"
		    + "        a.empcode,\r\n"
		    + "        a.checkindate,\r\n"
		    + "        CASE \r\n"
		    + "            WHEN SUM(a.effectivehours) >= MAX(sm.fulldayhours) THEN 1\r\n"
		    + "            WHEN SUM(a.effectivehours) >= MAX(sm.halfdayhours) THEN 0.5\r\n"
		    + "            ELSE 0\r\n"
		    + "        END AS present_value\r\n"
		    + "    FROM attendancedaily a\r\n"
		    + "    JOIN shiftassigndetails sd \r\n"
		    + "        ON a.empcode = sd.employeecode\r\n"
		    + "       AND a.checkindate BETWEEN sd.effectivefrom AND sd.effectiveto\r\n"
		    + "    JOIN shiftmaster sm ON sm.shiftcode = sd.shiftcode\r\n"
		    + "    GROUP BY a.empcode, a.checkindate\r\n"
		    + "),\r\n"
		    + "\r\n"
		    + "res_present_days AS (\r\n"
		    + "    SELECT \r\n"
		    + "        a.empcode,\r\n"
		    + "        SUM(a.present_value) AS presentdays\r\n"
		    + "    FROM att_data a\r\n"
		    + "    JOIN separation_data sd ON sd.employeecode = a.empcode\r\n"
		    + "    WHERE a.checkindate BETWEEN \r\n"
		    + "        DATE_FORMAT(sd.resignation,'%Y-%m-01')\r\n"
		    + "        AND DATE_SUB(sd.resignation, INTERVAL 1 DAY)\r\n"
		    + "    GROUP BY a.empcode\r\n"
		    + "),\r\n"
		    + "\r\n"
		    + "weekoffs AS (\r\n"
		    + "    SELECT DISTINCT ds.dt AS weekoffdate, eb.employeecode\r\n"
		    + "    FROM date_series ds\r\n"
		    + "    JOIN emp_base eb ON eb.weekoffeligible = 1\r\n"
		    + "    JOIN companyweekoff cw\r\n"
		    + "        ON cw.companyid = ?1\r\n"
		    + "       AND UPPER(DAYNAME(ds.dt)) = UPPER(cw.weekoffdays)\r\n"
		    + "    JOIN weekoffoccurrences wo\r\n"
		    + "        ON wo.companyweekoffid = cw.companyweekoffid\r\n"
		    + "    WHERE wo.weeknumber = -1\r\n"
		    + "       OR wo.weeknumber = (1 + FLOOR((DAY(ds.dt) - 1) / 7))\r\n"
		    + "),\r\n"
		    + "\r\n"
		    + "weekoff_res AS (\r\n"
		    + "    SELECT w.employeecode, COUNT(*) AS weekoff_res\r\n"
		    + "    FROM weekoffs w\r\n"
		    + "    JOIN separation_data sd ON sd.employeecode = w.employeecode\r\n"
		    + "    LEFT JOIN attendancedaily a\r\n"
		    + "        ON a.empcode = w.employeecode\r\n"
		    + "       AND a.checkindate = w.weekoffdate\r\n"
		    + "    WHERE w.weekoffdate BETWEEN \r\n"
		    + "        DATE_FORMAT(sd.resignation,'%Y-%m-01')\r\n"
		    + "        AND DATE_SUB(sd.resignation, INTERVAL 1 DAY)\r\n"
		    + "      AND a.empcode IS NULL\r\n"
		    + "    GROUP BY w.employeecode\r\n"
		    + "),\r\n"
		    + "\r\n"
		    + "holidays_cte AS (\r\n"
		    + "    SELECT h.holidaydate, eb.employeecode\r\n"
		    + "    FROM holidays h\r\n"
		    + "    JOIN emp_base eb ON 1=1\r\n"
		    + "    LEFT JOIN attendancedaily a\r\n"
		    + "        ON a.empcode = eb.employeecode\r\n"
		    + "       AND a.checkindate = h.holidaydate\r\n"
		    + "    WHERE h.orgid = ?1\r\n"
		    + "      AND a.empcode IS NULL\r\n"
		    + "),\r\n"
		    + "\r\n"
		    + "holiday_res AS (\r\n"
		    + "    SELECT h.employeecode, COUNT(*) AS holidays_res\r\n"
		    + "    FROM holidays_cte h\r\n"
		    + "    JOIN separation_data sd ON sd.employeecode = h.employeecode\r\n"
		    + "    WHERE h.holidaydate BETWEEN \r\n"
		    + "        DATE_FORMAT(sd.resignation,'%Y-%m-01')\r\n"
		    + "        AND sd.resignation\r\n"
		    + "    GROUP BY h.employeecode\r\n"
		    + "),\r\n"
		    + "\r\n"
		    + "res_leave_days AS (\r\n"
		    + "    SELECT l.employeecode, SUM(l.totalleave) AS leaves\r\n"
		    + "    FROM approvalleaves l\r\n"
		    + "    JOIN separation_data sd ON sd.employeecode = l.employeecode\r\n"
		    + "    WHERE l.leavetype != 'LOSS OF PAY'\r\n"
		    + "      AND l.leavedate BETWEEN \r\n"
		    + "        DATE_FORMAT(sd.resignation,'%Y-%m-01')\r\n"
		    + "        AND sd.resignation\r\n"
		    + "    GROUP BY l.employeecode\r\n"
		    + "),\r\n"
		    + "\r\n"
		    + "lop_res AS (\r\n"
		    + "    SELECT l.employeecode, SUM(l.totalleave) AS lop\r\n"
		    + "    FROM approvalleaves l\r\n"
		    + "    JOIN separation_data sd ON sd.employeecode = l.employeecode\r\n"
		    + "    WHERE l.leavetype = 'LOSS OF PAY'\r\n"
		    + "      AND l.leavedate BETWEEN \r\n"
		    + "        DATE_FORMAT(sd.resignation,'%Y-%m-01')\r\n"
		    + "        AND sd.resignation\r\n"
		    + "    GROUP BY l.employeecode\r\n"
		    + "),\r\n"
		    + "\r\n"
		    + "salary_info AS (\r\n"
		    + "    SELECT employeecode, sumofearning, sumofdetection\r\n"
		    + "    FROM salarystructure\r\n"
		    + "),\r\n"
		    + "\r\n"
		    + "base AS (\r\n"
		    + "    SELECT\r\n"
		    + "        eb.employeecode,\r\n"
		    + "        eb.employee,\r\n"
		    + "        sd.resignation,\r\n"
		    + "        sd.lastworkingdate,\r\n"
		    + "\r\n"
		    + "        ROUND(\r\n"
		    + "        (\r\n"
		    + "            (\r\n"
		    + "                COALESCE(rp.presentdays, 0)\r\n"
		    + "              + COALESCE(wr.weekoff_res, 0)\r\n"
		    + "              + COALESCE(hr.holidays_res, 0)\r\n"
		    + "              + COALESCE(rl.leaves, 0)\r\n"
		    + "              - COALESCE(lp.lop, 0)\r\n"
		    + "            )\r\n"
		    + "            +\r\n"
		    + "            DATEDIFF(\r\n"
		    + "                LAST_DAY(sd.resignation),\r\n"
		    + "                DATE_SUB(sd.resignation, INTERVAL 1 DAY)\r\n"
		    + "            )\r\n"
		    + "        ),1) AS res_month_working_days,\r\n"
		    + "\r\n"
		    + "        DAY(LAST_DAY(sd.resignation)) AS res_month_days,\r\n"
		    + "\r\n"
		    + "        DAY(LAST_DAY(sd.lastworkingdate)) AS next_month_days,\r\n"
		    + "\r\n"
		    + "        DATEDIFF(\r\n"
		    + "            sd.lastworkingdate,\r\n"
		    + "            DATE_FORMAT(sd.lastworkingdate,'%Y-%m-01')\r\n"
		    + "        ) + 1 AS next_month_worked_days,\r\n"
		    + "\r\n"
		    + "        si.sumofearning,\r\n"
		    + "        si.sumofdetection\r\n"
		    + "\r\n"
		    + "    FROM separation_data sd\r\n"
		    + "    JOIN emp_base eb ON eb.employeecode = sd.employeecode\r\n"
		    + "    LEFT JOIN res_present_days rp ON rp.empcode = eb.employeecode\r\n"
		    + "    LEFT JOIN weekoff_res wr ON wr.employeecode = eb.employeecode\r\n"
		    + "    LEFT JOIN holiday_res hr ON hr.employeecode = eb.employeecode\r\n"
		    + "    LEFT JOIN res_leave_days rl ON rl.employeecode = eb.employeecode\r\n"
		    + "    LEFT JOIN lop_res lp ON lp.employeecode = eb.employeecode\r\n"
		    + "    LEFT JOIN salary_info si ON si.employeecode = eb.employeecode\r\n"
		    + "),\r\n"
		    + "\r\n"
		    + "months AS (\r\n"
		    + "    SELECT \r\n"
		    + "        employeecode, employee,\r\n"
		    + "        DATE_FORMAT(resignation,'%Y-%m-01') AS mth,\r\n"
		    + "        resignation, lastworkingdate,\r\n"
		    + "        res_month_working_days, res_month_days,\r\n"
		    + "        next_month_worked_days, next_month_days,\r\n"
		    + "        sumofearning, sumofdetection\r\n"
		    + "    FROM base\r\n"
		    + "\r\n"
		    + "    UNION ALL\r\n"
		    + "\r\n"
		    + "    SELECT \r\n"
		    + "        employeecode, employee,\r\n"
		    + "        DATE_ADD(mth, INTERVAL 1 MONTH),\r\n"
		    + "        resignation, lastworkingdate,\r\n"
		    + "        res_month_working_days, res_month_days,\r\n"
		    + "        next_month_worked_days, next_month_days,\r\n"
		    + "        sumofearning, sumofdetection\r\n"
		    + "    FROM months\r\n"
		    + "    WHERE mth < DATE_FORMAT(lastworkingdate,'%Y-%m-01')\r\n"
		    + "),\r\n"
		    + "\r\n"
		    + "-- ✅ ONLY CHANGE HERE\r\n"
		    + "final AS (\r\n"
		    + "    SELECT \r\n"
		    + "        employeecode,\r\n"
		    + "        employee,\r\n"
		    + "        resignation,\r\n"
		    + "        lastworkingdate,\r\n"
		    + "        DATE_FORMAT(mth,'%b-%Y') AS month,\r\n"
		    + "\r\n"
		    + "        CASE \r\n"
		    + "            WHEN DATE_FORMAT(mth,'%Y-%m') = DATE_FORMAT(resignation,'%Y-%m')\r\n"
		    + "                THEN res_month_working_days\r\n"
		    + "            WHEN DATE_FORMAT(mth,'%Y-%m') = DATE_FORMAT(lastworkingdate,'%Y-%m')\r\n"
		    + "                THEN next_month_worked_days\r\n"
		    + "            ELSE DAY(LAST_DAY(mth))\r\n"
		    + "        END AS payable_days,\r\n"
		    + "\r\n"
		    + "        CASE \r\n"
		    + "            WHEN DATE_FORMAT(mth,'%Y-%m') = DATE_FORMAT(resignation,'%Y-%m')\r\n"
		    + "                THEN res_month_days\r\n"
		    + "            ELSE DAY(LAST_DAY(mth))\r\n"
		    + "        END AS total_days,\r\n"
		    + "\r\n"
		    + "        sumofearning,\r\n"
		    + "\r\n"
		    + "        CASE \r\n"
		    + "    WHEN DATE_FORMAT(mth,'%Y-%m') = DATE_FORMAT(lastworkingdate,'%Y-%m')\r\n"
		    + "        THEN \r\n"
		    + "        (\r\n"
		    + "            sumofdetection /\r\n"
		    + "            (\r\n"
		    + "                CASE \r\n"
		    + "                    WHEN DATE_FORMAT(mth,'%Y-%m') = DATE_FORMAT(resignation,'%Y-%m')\r\n"
		    + "                        THEN res_month_days\r\n"
		    + "                    ELSE DAY(LAST_DAY(mth))\r\n"
		    + "                END\r\n"
		    + "            )\r\n"
		    + "        )\r\n"
		    + "        *\r\n"
		    + "        (\r\n"
		    + "            CASE \r\n"
		    + "                WHEN DATE_FORMAT(mth,'%Y-%m') = DATE_FORMAT(resignation,'%Y-%m')\r\n"
		    + "                    THEN res_month_working_days\r\n"
		    + "                WHEN DATE_FORMAT(mth,'%Y-%m') = DATE_FORMAT(lastworkingdate,'%Y-%m')\r\n"
		    + "                    THEN next_month_worked_days\r\n"
		    + "                ELSE DAY(LAST_DAY(mth))\r\n"
		    + "            END\r\n"
		    + "        )\r\n"
		    + "    ELSE sumofdetection\r\n"
		    + "END AS sumofdetection\r\n"
		    + "\r\n"
		    + "    FROM months\r\n"
		    + ")\r\n"
		    + "\r\n"
		    + "-- 🔹 FINAL OUTPUT\r\n"
		    + "SELECT \r\n"
		    + "    employeecode,\r\n"
		    + "    employee,\r\n"
		    + "    resignation,\r\n"
		    + "    lastworkingdate,\r\n"
		    + "\r\n"
		    + "    DATE_ADD(\r\n"
		    + "        lastworkingdate,\r\n"
		    + "        INTERVAL CEIL(COALESCE((\r\n"
		    + "            SELECT SUM(l.totalleave)\r\n"
		    + "            FROM approvalleaves l\r\n"
		    + "            WHERE l.employeecode = final.employeecode \r\n"
		    + "              AND l.leavetype = 'LOSS OF PAY'\r\n"
		    + "              AND l.leavedate BETWEEN final.resignation AND final.lastworkingdate\r\n"
		    + "        ),0)) DAY\r\n"
		    + "    ) AS finalworkingdate,\r\n"
		    + "\r\n"
		    + "    month,\r\n"
		    + "    total_days,\r\n"
		    + "    payable_days,\r\n"
		    + "    sumofearning,\r\n"
		    + "    sumofdetection,\r\n"
		    + "\r\n"
		    + "    ROUND(sumofearning / total_days,2) AS per_day_salary,\r\n"
		    + "    ROUND((sumofearning / total_days) * payable_days,2) AS gross_salary,\r\n"
		    + "\r\n"
		    + "    -- ✅ FIXED\r\n"
		    + "    ROUND(\r\n"
		    + "        ((sumofearning / total_days) * payable_days)\r\n"
		    + "        - sumofdetection\r\n"
		    + "    ,2) AS net_salary\r\n"
		    + "\r\n"
		    + "FROM final;"
		)
	Set<Object[]> getpayslipSettlementDetails(Long orgId, String empCode,String branchCode);
}