package com.efit.hrms.repo;

import java.util.List;
import java.util.Map;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Service;

import com.efit.hrms.entity.CheckInStatusVO;

@Service
public interface CheckInStatusRepo extends JpaRepository<CheckInStatusVO, Long>{


	@Query(nativeQuery = true, value = "SELECT \r\n"
			+ "    cs.*, \r\n"
			+ "    ci_in.latestIn, \r\n"
			+ "    ci_out.latestOut\r\n"
			+ "FROM \r\n"
			+ "    checkinstatus cs\r\n"
			+ "LEFT JOIN (\r\n"
			+ "    SELECT \r\n"
			+ "        c1.empcode, \r\n"
			+ "        c1.entrytime AS latestIn\r\n"
			+ "    FROM \r\n"
			+ "        checkin c1\r\n"
			+ "    INNER JOIN (\r\n"
			+ "        SELECT empcode, MAX(createdOn) AS max_createdon\r\n"
			+ "        FROM checkin\r\n"
			+ "        WHERE status = 'In'\r\n"
			+ "        GROUP BY empcode\r\n"
			+ "    ) c2 \r\n"
			+ "    ON c1.empcode = c2.empcode AND c1.createdOn = c2.max_createdon\r\n"
			+ "    WHERE c1.status = 'In'\r\n"
			+ ") ci_in \r\n"
			+ "ON cs.empcode = ci_in.empcode\r\n"
			+ "LEFT JOIN (\r\n"
			+ "    SELECT \r\n"
			+ "        c3.empcode, \r\n"
			+ "        c3.entrytime AS latestOut\r\n"
			+ "    FROM \r\n"
			+ "        checkin c3\r\n"
			+ "    INNER JOIN (\r\n"
			+ "        SELECT empcode, MAX(createdOn) AS max_createdon\r\n"
			+ "        FROM checkin\r\n"
			+ "        WHERE status = 'Out'\r\n"
			+ "        GROUP BY empcode\r\n"
			+ "    ) c4 \r\n"
			+ "    ON c3.empcode = c4.empcode AND c3.createdOn = c4.max_createdon\r\n"
			+ "    WHERE c3.status = 'Out'\r\n"
			+ ") ci_out \r\n"
			+ "ON cs.empcode = ci_out.empcode\r\n"
			+ "WHERE \r\n"
			+ "    cs.empcode =?1 \r\n"
			+ "ORDER BY \r\n"
			+ "    checkinstatusid DESC\r\n"
			+ "LIMIT 1 ")
	List<Object[]> findByempcode(String empcode);

	Optional<CheckInStatusVO> findById(String empcode);

	Optional<CheckInStatusVO> findTopByEmpcodeAndOrgIdAndBranchOrderByIdDesc(String empcode, long orgId, String branch);

//	@Query(nativeQuery = true, value = 
//			    "SELECT \r\n"
//			    + "    a.id, \r\n"
//			    + "    a.empcode, \r\n"
//			    + "    a.entrydate, \r\n"
//			    + "    a.checkInTime, \r\n"
//			    + "    a.checkOutTime,\r\n"
//			    + "    CAST(a.effectivefrom AS CHAR) AS effectivefrom,\r\n"
//			    + "    CAST(a.TotalWorkingHours AS CHAR) AS TotalWorkingHours,\r\n"
//			    + "    b.approvalstatus\r\n"
//			    + "FROM attendancetime a\r\n"
//			    + "JOIN checkin b \r\n"
//			    + "    ON a.empcode = b.empcode \r\n"
//			    + "    AND a.entrydate = b.checkindate \r\n"
//			    + "    AND a.checkinTime = b.entrytime\r\n"
//			    + "WHERE a.empcode =?1 \r\n"
//			    + "  AND a.entrydate IS NOT NULL\r\n"
//			    + "ORDER BY a.entrydate DESC"
//		)
//		List<Map<String, Object>> findByEmpcode(String empcode);

	

	
	
//	@Query(nativeQuery = true, value =
//	        "WITH\r\n"
//	        + "MonthRange AS (\r\n"
//	        + "    SELECT\r\n"
//	        + "        MAKEDATE(2025, 1) + INTERVAL (?2 - 1) MONTH AS start_date,\r\n"
//	        + "        LAST_DAY(MAKEDATE(2025, 1) + INTERVAL (?2 - 1) MONTH) AS end_date\r\n"
//	        + "),\r\n"
//	        + "Numbers AS (\r\n"
//	        + "    SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4\r\n"
//	        + "    UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9\r\n"
//	        + "    UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14\r\n"
//	        + "    UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19\r\n"
//	        + "    UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24\r\n"
//	        + "    UNION ALL SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29\r\n"
//	        + "    UNION ALL SELECT 30 UNION ALL SELECT 31\r\n"
//	        + "),\r\n"
//	        + "DateRange AS (\r\n"
//	        + "    SELECT DATE_ADD(start_date, INTERVAL n DAY) AS entrydate\r\n"
//	        + "    FROM MonthRange CROSS JOIN Numbers\r\n"
//	        + "    WHERE DATE_ADD(start_date, INTERVAL n DAY) <= LEAST(end_date, CURDATE())\r\n"
//	        + "),\r\n"
//	        + "RawData AS (\r\n"
//	        + "    SELECT checkindate, empcode, entrytime, createdon, status, approvalstatus\r\n"
//	        + "    FROM checkin\r\n"
//	        + "    WHERE orgid = ?3 AND branch = ?4 AND status IN ('In','Out')\r\n"
//	        + "    \r\n"
//	        + "    UNION ALL\r\n"
//	        + "    \r\n"
//	        + "    SELECT checkindate, empcode, entrytime, createdon, status, approvalstatus\r\n"
//	        + "    FROM checkinoutadjustment\r\n"
//	        + "    WHERE orgid = ?3 AND branch = ?4 AND status IN ('In','Out') AND approvalstatus IN ('Approved','PENDING')\r\n"
//	        + "),\r\n"
//	        + "Filtered AS (\r\n"
//	        + "    SELECT * FROM RawData WHERE empcode = ?1\r\n"
//	        + "),\r\n"
//	        + "FirstIn AS (\r\n"
//	        + "    SELECT checkindate, empcode, MIN(entrytime) AS first_in\r\n"
//	        + "    FROM Filtered\r\n"
//	        + "    WHERE status = 'In'\r\n"
//	        + "    GROUP BY checkindate, empcode\r\n"
//	        + "),\r\n"
//	        + "LastOut AS (\r\n"
//	        + "    SELECT checkindate, empcode, entrytime AS last_out\r\n"
//	        + "    FROM (\r\n"
//	        + "        SELECT *, ROW_NUMBER() OVER (\r\n"
//	        + "            PARTITION BY checkindate, empcode\r\n"
//	        + "            ORDER BY createdon DESC\r\n"
//	        + "        ) AS rn\r\n"
//	        + "        FROM Filtered\r\n"
//	        + "        WHERE status = 'Out'\r\n"
//	        + "    ) x\r\n"
//	        + "    WHERE rn = 1\r\n"
//	        + "),\r\n"
//	        + "GrossCalc AS (\r\n"
//	        + "    SELECT fi.checkindate, fi.empcode,\r\n"
//	        + "           fi.first_in AS checkInTime,\r\n"
//	        + "           lo.last_out AS checkOutTime,\r\n"
//	        + "           CASE \r\n"
//	        + "               WHEN TIMESTAMPDIFF(SECOND, fi.first_in, lo.last_out) < 0 THEN '00:00:00'\r\n"
//	        + "               ELSE SEC_TO_TIME(TIMESTAMPDIFF(SECOND, fi.first_in, lo.last_out))\r\n"
//	        + "           END AS gross_hours\r\n"
//	        + "    FROM FirstIn fi\r\n"
//	        + "    LEFT JOIN LastOut lo USING (checkindate, empcode)\r\n"
//	        + "),\r\n"
//	        + "PairedIO AS (\r\n"
//	        + "    SELECT i.checkindate, i.empcode,\r\n"
//	        + "           TIMESTAMPDIFF(SECOND, i.entrytime, o.entrytime) AS secs\r\n"
//	        + "    FROM (\r\n"
//	        + "        SELECT *,\r\n"
//	        + "            ROW_NUMBER() OVER (\r\n"
//	        + "                PARTITION BY checkindate, empcode\r\n"
//	        + "                ORDER BY createdon\r\n"
//	        + "            ) AS rn\r\n"
//	        + "        FROM Filtered\r\n"
//	        + "    ) i\r\n"
//	        + "    JOIN (\r\n"
//	        + "        SELECT *,\r\n"
//	        + "            ROW_NUMBER() OVER (\r\n"
//	        + "                PARTITION BY checkindate, empcode\r\n"
//	        + "                ORDER BY createdon\r\n"
//	        + "            ) AS rn\r\n"
//	        + "        FROM Filtered\r\n"
//	        + "    ) o\r\n"
//	        + "    USING (checkindate, empcode)\r\n"
//	        + "    WHERE i.status = 'In' AND o.status = 'Out' AND o.rn = i.rn + 1\r\n"
//	        + "),\r\n"
//	        + "EffectiveDurations AS (\r\n"
//	        + "    SELECT checkindate, empcode,\r\n"
//	        + "           CASE \r\n"
//	        + "               WHEN SUM(secs) < 0 THEN '00:00:00'\r\n"
//	        + "               ELSE SEC_TO_TIME(SUM(secs))\r\n"
//	        + "           END AS effective_hours\r\n"
//	        + "    FROM PairedIO\r\n"
//	        + "    GROUP BY checkindate, empcode\r\n"
//	        + "),\r\n"
//	        + "Leaves AS (\r\n"
//	        + "    SELECT leavedate\r\n"
//	        + "    FROM approvalleaves\r\n"
//	        + "    WHERE employeecode = ?1 AND branchcode = ?5 AND orgid = ?3\r\n"
//	        + "    AND leavedate BETWEEN (SELECT start_date FROM MonthRange)\r\n"
//	        + "                     AND (SELECT end_date FROM MonthRange)\r\n"
//	        + "),\r\n"
//	        + "HolidayList AS (\r\n"
//	        + "    SELECT holidaydate\r\n"
//	        + "    FROM holidays\r\n"
//	        + "    WHERE branchcode = ?5 AND orgid = ?3\r\n"
//	        + "    AND holidaydate BETWEEN (SELECT start_date FROM MonthRange)\r\n"
//	        + "                       AND (SELECT end_date FROM MonthRange)\r\n"
//	        + "),\r\n"
//	        + "WeekOffs AS (\r\n"
//	        + "    SELECT d.entrydate AS weekoffdate\r\n"
//	        + "    FROM DateRange d\r\n"
//	        + "    JOIN companyweekoff wo ON DAYNAME(d.entrydate) = wo.weekoffdays\r\n"
//	        + "    JOIN branch b ON wo.companyid = b.orgid AND b.branchcode = ?5\r\n"
//	        + "),\r\n"
//	        + "LatestApproval AS (\r\n"
//	        + "    SELECT checkindate, empcode, approvalstatus\r\n"
//	        + "    FROM (\r\n"
//	        + "        SELECT checkindate, empcode, approvalstatus,\r\n"
//	        + "               ROW_NUMBER() OVER (\r\n"
//	        + "                   PARTITION BY checkindate, empcode\r\n"
//	        + "                   ORDER BY createdon DESC\r\n"
//	        + "               ) AS rn\r\n"
//	        + "        FROM Filtered\r\n"
//	        + "        WHERE approvalstatus IS NOT NULL\r\n"
//	        + "    ) x\r\n"
//	        + "    WHERE rn = 1\r\n"
//	        + "),\r\n"
//	        + "FinalAttendance AS (\r\n"
//	        + "    SELECT\r\n"
//	        + "        d.entrydate,\r\n"
//	        + "        ?1 AS empcode,\r\n"
//	        + "        COALESCE(g.checkInTime, '00:00:00') AS checkInTime,\r\n"
//	        + "        COALESCE(g.checkOutTime, '00:00:00') AS checkOutTime,\r\n"
//	        + "        CASE\r\n"
//	        + "            WHEN g.checkInTime IS NOT NULL THEN 'Present'\r\n"
//	        + "            WHEN l.leavedate IS NOT NULL THEN 'Leave'\r\n"
//	        + "            WHEN h.holidaydate IS NOT NULL THEN 'Holiday'\r\n"
//	        + "            WHEN w.weekoffdate IS NOT NULL THEN 'WeekOff'\r\n"
//	        + "            ELSE 'Absent'\r\n"
//	        + "        END AS attendancestatus,\r\n"
//	        + "        COALESCE(g.gross_hours, '00:00:00') AS grosshours,\r\n"
//	        + "        COALESCE(e.effective_hours, '00:00:00') AS effectivehours,\r\n"
//	        + "        a.approvalstatus AS approvalstatus\r\n"
//	        + "    FROM DateRange d\r\n"
//	        + "    LEFT JOIN GrossCalc g ON g.checkindate = d.entrydate\r\n"
//	        + "    LEFT JOIN EffectiveDurations e ON e.checkindate = d.entrydate\r\n"
//	        + "    LEFT JOIN Leaves l ON l.leavedate = d.entrydate\r\n"
//	        + "    LEFT JOIN HolidayList h ON h.holidaydate = d.entrydate\r\n"
//	        + "    LEFT JOIN WeekOffs w ON w.weekoffdate = d.entrydate\r\n"
//	        + "    LEFT JOIN LatestApproval a ON a.checkindate = d.entrydate AND a.empcode = ?1\r\n"
//	        + ")\r\n"
//	        + "SELECT *\r\n"
//	        + "FROM FinalAttendance\r\n"
//	        + "WHERE attendancestatus IN ('Present', 'Absent')\r\n"
//	        + "ORDER BY entrydate DESC;\r\n"
//	        + "\r\n"
//	        + "\r\n"
//	        + ""
//	)	List<Map<String, Object>> findByEmpcode(
//    String empcode, 
//    int month, 
//    String orgId, 
//    String branch, 
//    String branchCode
//);
	
	
	//08-10-2025
//	@Query(nativeQuery = true, value = "WITH\r\n"
//			+ "MonthRange AS (\r\n"
//			+ "    SELECT\r\n"
//			+ "        MAKEDATE(2025, 1) + INTERVAL (?2 - 1) MONTH AS start_date,\r\n"
//			+ "        LAST_DAY(MAKEDATE(2025, 1) + INTERVAL (?2 - 1) MONTH) AS end_date\r\n"
//			+ "),\r\n"
//			+ "Numbers AS (\r\n"
//			+ "    SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4\r\n"
//			+ "    UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9\r\n"
//			+ "    UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14\r\n"
//			+ "    UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19\r\n"
//			+ "    UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24\r\n"
//			+ "    UNION ALL SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29\r\n"
//			+ "    UNION ALL SELECT 30 UNION ALL SELECT 31\r\n"
//			+ "),\r\n"
//			+ "DateRange AS (\r\n"
//			+ "    SELECT DATE_ADD(start_date, INTERVAL n DAY) AS entrydate\r\n"
//			+ "    FROM MonthRange CROSS JOIN Numbers\r\n"
//			+ "    WHERE DATE_ADD(start_date, INTERVAL n DAY) <= LEAST(end_date, CURDATE())\r\n"
//			+ "),\r\n"
//			+ "AttendanceData AS (\r\n"
//			+ "    SELECT\r\n"
//			+ "        checkindate,\r\n"
//			+ "        empcode,\r\n"
//			+ "        intime AS checkInTime,\r\n"
//			+ "        outtime AS checkOutTime,\r\n"
//			+ "        grosshours,\r\n"
//			+ "        effectivehours\r\n"
//			+ "    FROM attendancedaily\r\n"
//			+ "    WHERE orgid = ?3 AND branchcode = ?4 AND empcode = ?1\r\n"
//			+ "),\r\n"
//			+ "Leaves AS (\r\n"
//			+ "    SELECT leavedate\r\n"
//			+ "    FROM approvalleaves\r\n"
//			+ "    WHERE employeecode = ?1 AND branchcode = ?4 AND orgid = ?3\r\n"
//			+ "    AND leavedate BETWEEN (SELECT start_date FROM MonthRange)\r\n"
//			+ "                     AND (SELECT end_date FROM MonthRange)\r\n"
//			+ "),\r\n"
//			+ "HolidayList AS (\r\n"
//			+ "    SELECT holidaydate\r\n"
//			+ "    FROM holidays\r\n"
//			+ "    WHERE branchcode = ?4 AND orgid = ?3\r\n"
//			+ "    AND holidaydate BETWEEN (SELECT start_date FROM MonthRange)\r\n"
//			+ "                       AND (SELECT end_date FROM MonthRange)\r\n"
//			+ "),\r\n"
//			+ "WeekOffs AS (\r\n"
//			+ "    SELECT d.entrydate AS weekoffdate\r\n"
//			+ "    FROM DateRange d\r\n"
//			+ "    JOIN companyweekoff wo ON DAYNAME(d.entrydate) = wo.weekoffdays\r\n"
//			+ "    JOIN branch b ON wo.companyid = b.orgid AND b.branchcode = ?4\r\n"
//			+ ")\r\n"
//			+ "SELECT\r\n"
//			+ "    d.entrydate,\r\n"
//			+ "    ?1 AS empcode,\r\n"
//			+ "    COALESCE(a.checkInTime, '00:00:00') AS checkInTime,\r\n"
//			+ "    COALESCE(a.checkOutTime, '00:00:00') AS checkOutTime,\r\n"
//			+ "    CASE\r\n"
//			+ "        WHEN a.checkindate IS NOT NULL THEN 'Present'\r\n"
//			+ "        WHEN l.leavedate IS NOT NULL THEN 'Leave'\r\n"
//			+ "        WHEN h.holidaydate IS NOT NULL THEN 'Holiday'\r\n"
//			+ "        WHEN w.weekoffdate IS NOT NULL THEN 'WeekOff'\r\n"
//			+ "        ELSE 'Absent'\r\n"
//			+ "    END AS attendancestatus,\r\n"
//			+ "    COALESCE(a.grosshours, '0') AS grosshours,\r\n"
//			+ "    COALESCE(a.effectivehours, '0') AS effectivehours\r\n"
//			+ "FROM DateRange d\r\n"
//			+ "LEFT JOIN AttendanceData a ON a.checkindate = d.entrydate\r\n"
//			+ "LEFT JOIN Leaves l ON l.leavedate = d.entrydate\r\n"
//			+ "LEFT JOIN HolidayList h ON h.holidaydate = d.entrydate\r\n"
//			+ "LEFT JOIN WeekOffs w ON w.weekoffdate = d.entrydate\r\n"
//			+ "WHERE\r\n"
//			+ "    (a.checkindate IS NOT NULL OR l.leavedate IS NULL OR h.holidaydate IS NULL OR w.weekoffdate IS NULL)\r\n"
//			+ "ORDER BY d.entrydate DESC;\r\n"
//			+ "")
//	List<Map<String, Object>> findByEmpcode(
//	    String empcode, 
//	    int month, 
//	    String orgId, 
//	    String branchCode
//	);
	
	
	@Query(nativeQuery = true, value = "WITH\r\n"
			+ "MonthRange AS (\r\n"
			+ "    SELECT\r\n"
			+ "        MAKEDATE(CAST(?5 AS UNSIGNED), 1) + INTERVAL (?2 - 1) MONTH AS start_date,\r\n"
			+ "        LAST_DAY(MAKEDATE(CAST(?5 AS UNSIGNED), 1) + INTERVAL (?2 - 1) MONTH) AS end_date\r\n"
			+ "),\r\n"
			+ "\r\n"
			+ "Numbers AS (\r\n"
			+ "    SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4\r\n"
			+ "    UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9\r\n"
			+ "    UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14\r\n"
			+ "    UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19\r\n"
			+ "    UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24\r\n"
			+ "    UNION ALL SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29\r\n"
			+ "    UNION ALL SELECT 30 UNION ALL SELECT 31\r\n"
			+ "),\r\n"
			+ "\r\n"
			+ "DateRange AS (\r\n"
			+ "    SELECT DATE_ADD(start_date, INTERVAL n DAY) AS entrydate\r\n"
			+ "    FROM MonthRange\r\n"
			+ "    CROSS JOIN Numbers\r\n"
			+ "    WHERE DATE_ADD(start_date, INTERVAL n DAY)\r\n"
			+ "          <= LEAST(end_date, CURDATE())\r\n"
			+ "),\r\n"
			+ "\r\n"
			+ "emp_base AS (\r\n"
			+ "    SELECT e.employeecode, e.employee, e.department, e.branch, e.branchcode, e.weekoffeligible\r\n"
			+ "    FROM employee e\r\n"
			+ "    WHERE e.active = 1\r\n"
			+ "      AND e.orgid = ?3\r\n"
			+ "      AND e.employeecode = ?1\r\n"
			+ "),\r\n"
			+ "\r\n"
			+ "AttendanceData AS (\r\n"
			+ "    SELECT\r\n"
			+ "        checkindate,\r\n"
			+ "        empcode,\r\n"
			+ "        intime AS checkInTime,\r\n"
			+ "        outtime AS checkOutTime,\r\n"
			+ "        grosshours,\r\n"
			+ "        effectivehours\r\n"
			+ "    FROM attendancedaily\r\n"
			+ "    WHERE orgid = ?3\r\n"
			+ "      AND branchcode = ?4\r\n"
			+ "      AND empcode = ?1\r\n"
			+ "),\r\n"
			+ "\r\n"
			+ "Leaves AS (\r\n"
			+ "    SELECT leavedate\r\n"
			+ "    FROM approvalleaves\r\n"
			+ "    WHERE employeecode = ?1\r\n"
			+ "      AND branchcode = ?4\r\n"
			+ "      AND orgid = ?3\r\n"
			+ "      AND leavedate BETWEEN\r\n"
			+ "            (SELECT start_date FROM MonthRange)\r\n"
			+ "        AND (SELECT end_date FROM MonthRange)\r\n"
			+ "    GROUP BY leavedate\r\n"
			+ "),\r\n"
			+ "\r\n"
			+ "holidays_cte AS (\r\n"
			+ "    SELECT holidaydate\r\n"
			+ "    FROM holidays\r\n"
			+ "    WHERE orgid = ?3\r\n"
			+ "      AND branchcode = ?4\r\n"
			+ "      AND active = 1\r\n"
			+ "      AND cancel = 0\r\n"
			+ "      AND holidaydate BETWEEN\r\n"
			+ "            (SELECT start_date FROM MonthRange)\r\n"
			+ "        AND (SELECT end_date FROM MonthRange)\r\n"
			+ "),\r\n"
			+ "\r\n"
			+ "weekoffs AS (\r\n"
			+ "    SELECT DISTINCT  ds.entrydate AS weekoffdate\r\n"
			+ "    FROM DateRange ds\r\n"
			+ "    JOIN companyweekoff cw\r\n"
			+ "      ON cw.companyid = ?3\r\n"
			+ "     AND UPPER(DAYNAME(ds.entrydate)) = UPPER(cw.weekoffdays)\r\n"
			+ "    JOIN emp_base eb\r\n"
			+ "      ON eb.weekoffeligible = 1\r\n"
			+ "),\r\n"
			+ "\r\n"
			+ "ApprovalStatusCTE AS (\r\n"
			+ "    SELECT\r\n"
			+ "        d.entrydate,\r\n"
			+ "        CASE\r\n"
			+ "            WHEN EXISTS (\r\n"
			+ "                SELECT 1\r\n"
			+ "                FROM checkin ci\r\n"
			+ "                WHERE ci.empcode = ?1\r\n"
			+ "                  AND ci.branchcode = ?4\r\n"
			+ "                  AND ci.orgid = ?3\r\n"
			+ "                  AND ci.checkindate = d.entrydate\r\n"
			+ "                  AND ci.approvalstatus = 'Pending'\r\n"
			+ "            )\r\n"
			+ "            OR EXISTS (\r\n"
			+ "                SELECT 1\r\n"
			+ "                FROM checkinoutadjustment ca\r\n"
			+ "                WHERE ca.empcode = ?1\r\n"
			+ "                  AND ca.branchcode = ?4\r\n"
			+ "                  AND ca.orgid = ?3\r\n"
			+ "                  AND ca.checkindate = d.entrydate\r\n"
			+ "                  AND ca.approvalstatus = 'Pending'\r\n"
			+ "            )\r\n"
			+ "            THEN 'Pending'\r\n"
			+ "\r\n"
			+ "            WHEN EXISTS (\r\n"
			+ "                SELECT 1\r\n"
			+ "                FROM checkin ci\r\n"
			+ "                WHERE ci.empcode = ?1\r\n"
			+ "                  AND ci.branchcode = ?4\r\n"
			+ "                  AND ci.orgid = ?3\r\n"
			+ "                  AND ci.checkindate = d.entrydate\r\n"
			+ "                  AND ci.approvalstatus = 'Approved'\r\n"
			+ "            )\r\n"
			+ "            OR EXISTS (\r\n"
			+ "                SELECT 1\r\n"
			+ "                FROM checkinoutadjustment ca\r\n"
			+ "                WHERE ca.empcode = ?1\r\n"
			+ "                  AND ca.branchcode = ?4\r\n"
			+ "                  AND ca.orgid = ?3\r\n"
			+ "                  AND ca.checkindate = d.entrydate\r\n"
			+ "                  AND ca.approvalstatus = 'Approved'\r\n"
			+ "            )\r\n"
			+ "            THEN 'Approved'\r\n"
			+ "\r\n"
			+ "            ELSE 'No Data'\r\n"
			+ "        END AS approvalstatus\r\n"
			+ "    FROM DateRange d\r\n"
			+ ")\r\n"
			+ "\r\n"
			+ "SELECT\r\n"
			+ "    d.entrydate,\r\n"
			+ "    ?1 AS empcode,\r\n"
			+ "    ap.approvalstatus,\r\n"
			+ "    COALESCE(a.checkInTime, '00:00:00') AS checkInTime,\r\n"
			+ "    COALESCE(a.checkOutTime, '00:00:00') AS checkOutTime,\r\n"
			+ "    CASE\r\n"
			+ "        WHEN ap.approvalstatus = 'Pending' THEN 'Pending'\r\n"
			+ "        WHEN ap.approvalstatus = 'Approved' THEN 'Approved'\r\n"
			+ "        WHEN a.checkindate IS NOT NULL THEN 'Present'\r\n"
			+ "        WHEN l.leavedate IS NOT NULL THEN 'Leave'\r\n"
			+ "        WHEN h.holidaydate IS NOT NULL THEN 'Holiday'\r\n"
			+ "        WHEN w.weekoffdate IS NOT NULL THEN 'WeekOff'\r\n"
			+ "        ELSE 'Absent'\r\n"
			+ "    END AS attendancestatus,\r\n"
			+ "    COALESCE(a.grosshours, '0') AS grosshours,\r\n"
			+ "    COALESCE(a.effectivehours, '0') AS effectivehours\r\n"
			+ "FROM DateRange d\r\n"
			+ "LEFT JOIN AttendanceData a ON a.checkindate = d.entrydate\r\n"
			+ "LEFT JOIN Leaves l ON l.leavedate = d.entrydate\r\n"
			+ "LEFT JOIN holidays_cte h ON h.holidaydate = d.entrydate\r\n"
			+ "LEFT JOIN weekoffs w ON w.weekoffdate = d.entrydate\r\n"
			+ "LEFT JOIN ApprovalStatusCTE ap ON ap.entrydate = d.entrydate\r\n"
			+ "ORDER BY d.entrydate DESC;\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "")
	List<Map<String, Object>> findByEmpcode(
	    String empcode, 
	    int month, 
	    String orgId, 
	    String branchCode, String finYear
	);


	@Query(nativeQuery = true, value = "SELECT DISTINCT \r\n"
			+ "    ad.empcode,\r\n"
			+ "    ad.empname,\r\n"
			+ "    ad.checkindate AS entrydate,\r\n"
			+ "    ad.intime AS CheckInTime,\r\n"
			+ "    ad.outtime AS CheckOutTime,\r\n"
			+ "    ad.grosshours AS TotalWorkingHours\r\n"
			+ "FROM attendancedaily ad\r\n"
			+ "WHERE ad.checkindate = ?3\r\n"
			+ "  AND ad.branch = ?2\r\n"
			+ "  AND ad.orgid = ?1\n"
			+ "")
	List<Map<String, Object>> getTodayAttendanceReportByOrgId(Long orgId, String branch, String date);



}
