package com.efit.hrms.repo;

import java.util.List;
import java.util.Set;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.efit.hrms.entity.InvestmentDeclarationVO;

@Repository
public interface InvestmentDeclarationRepo extends JpaRepository<InvestmentDeclarationVO, Long> {

	@Query(nativeQuery = true, value = "select * from investmentdeclaration where orgid=?1 and branch=?2 and employeecode=?3")
	List<InvestmentDeclarationVO> getInvestmentDeclarationDetails(Long orgId, String branch, String employeeCode);

	@Query(nativeQuery = true, value = "select * from investmentdeclaration where investmentdeclarationid=?1")
	InvestmentDeclarationVO getInvestmentDeclarationById(Long id);

	@Query(nativeQuery = true, value = "select sum(grossincome) as grossincome,sum(totaldedcutions) as totaldedcutions,sum(grossincome) - sum(totaldedcutions) as taxableincome,\r\n"
			+ "    round(( case\r\n" + "                when (sum(grossincome) - sum(totaldedcutions)) <= 400000 \r\n"
			+ "                then 0\r\n"
			+ "                when (sum(grossincome) - sum(totaldedcutions)) <= 800000 \r\n"
			+ "                then (\r\n"
			+ "                    ((sum(grossincome) - sum(totaldedcutions)) - 400000) * 5 / 100)\r\n"
			+ "                when (sum(grossincome) - sum(totaldedcutions)) <= 1200000 \r\n"
			+ "                then (400000 * 5 / 100 + ((sum(grossincome) - sum(totaldedcutions)) - 800000) * 10 / 100)\r\n"
			+ "                when (sum(grossincome) - sum(totaldedcutions)) <= 1600000 \r\n"
			+ "                then (400000 * 5 / 100 + 400000 * 10 / 100 + ((sum(grossincome) - sum(totaldedcutions)) - 1200000) * 15 / 100)\r\n"
			+ "                when (sum(grossincome) - sum(totaldedcutions)) <= 2000000 \r\n"
			+ "                then (400000 * 5 / 100 + 400000 * 10 / 100 + 400000 * 15 / 100 + ((sum(grossincome) - sum(totaldedcutions)) - 1600000) * 20 / 100)\r\n"
			+ "                when (sum(grossincome) - sum(totaldedcutions)) <= 2400000 \r\n"
			+ "                then (400000 * 5 / 100 + 400000 * 10 / 100 + 400000 * 15 / 100 + 400000 * 20 / 100 +\r\n"
			+ "                    ((sum(grossincome) - sum(totaldedcutions)) - 2000000) * 25 / 100)\r\n"
			+ "                else ( 400000 * 5 / 100 + 400000 * 10 / 100 + 400000 * 15 / 100 + 400000 * 20 / 100 + 400000 * 25 / 100 +\r\n"
			+ "                    ((sum(grossincome) - sum(totaldedcutions)) - 2400000) * 30 / 100) end\r\n"
			+ "            + (case\r\n" + "				when (sum(grossincome) - sum(totaldedcutions)) <= 400000 \r\n"
			+ "				then 0\r\n"
			+ "                    when (sum(grossincome) - sum(totaldedcutions)) <= 800000 \r\n"
			+ "                    then (\r\n"
			+ "                        ((sum(grossincome) - sum(totaldedcutions)) - 400000) * 5 / 100)\r\n"
			+ "                    when (sum(grossincome) - sum(totaldedcutions)) <= 1200000 \r\n"
			+ "                    then (400000 * 5 / 100 + ((sum(grossincome) - sum(totaldedcutions)) - 800000) * 10 / 100)\r\n"
			+ "                    when (sum(grossincome) - sum(totaldedcutions)) <= 1600000 \r\n"
			+ "                    then (400000 * 5 / 100 + 400000 * 10 / 100 + ((sum(grossincome) - sum(totaldedcutions)) - 1200000) * 15 / 100)\r\n"
			+ "                    when (sum(grossincome) - sum(totaldedcutions)) <= 2000000 \r\n"
			+ "                    then (400000 * 5 / 100 + 400000 * 10 / 100 + 400000 * 15 / 100 + ((sum(grossincome) - sum(totaldedcutions)) - 1600000) * 20 / 100)\r\n"
			+ "                    when (sum(grossincome) - sum(totaldedcutions)) <= 2400000 \r\n"
			+ "                    then (400000 * 5 / 100 + 400000 * 10 / 100 + 400000 * 15 / 100 + 400000 * 20 / 100 +\r\n"
			+ "                        ((sum(grossincome) - sum(totaldedcutions)) - 2000000) * 25 / 100)\r\n"
			+ "                    else (400000 * 5 / 100 + 400000 * 10 / 100 + 400000 * 15 / 100 + 400000 * 20 / 100 + 400000 * 25 / 100 +\r\n"
			+ "                        ((sum(grossincome) - sum(totaldedcutions)) - 2400000) * 30 / 100)\r\n"
			+ "                end\r\n" + "            ) * 4 / 100\r\n" + "        ) / 12 ,\r\n"
			+ "    2) AS monthlytds\r\n" + " from (\r\n"
			+ " select sum(amount) * 12 as grossincome ,0 as  totaldedcutions,0 as taxableincome,0 as monthlytds  from salarystructure\r\n"
			+ " where orgid=?1 and branch=?2 and employeecode=?3\r\n" + " union \r\n"
			+ " select 0 as grossincome ,sum(a1.declared) as  totaldedcutions,0 as taxableincome,0 as monthlytds  from investmentdeclaration a join\r\n"
			+ " investmentdeclarationdetails a1 on a.investmentdeclarationid=a1.investmentdeclarationid\r\n"
			+ " where a.orgid=?1 and a.branch=?2 and a.employeecode=?3\r\n" + " ) a")
	Set<Object[]> getDashBoardDetailsNew(Long orgId, String branch, String employeeCode);

	@Query(nativeQuery = true, value = "SELECT SUM(grossincome) AS grossincome,\r\n"
			+ "    SUM(totaldedcutions) AS totaldedcutions,\r\n"
			+ "    SUM(grossincome) - SUM(totaldedcutions) AS taxableincome,\r\n" + "    ROUND(( CASE\r\n"
			+ "                WHEN (SUM(grossincome) - SUM(totaldedcutions)) <= 250000\r\n"
			+ "                THEN 0\r\n"
			+ "                WHEN (SUM(grossincome) - SUM(totaldedcutions)) <= 500000\r\n"
			+ "                THEN (\r\n"
			+ "                    ((SUM(grossincome) - SUM(totaldedcutions)) - 250000) * 5 / 100\r\n"
			+ "                )\r\n" + "                WHEN (SUM(grossincome) - SUM(totaldedcutions)) <= 1000000\r\n"
			+ "                THEN (\r\n" + "                    (250000 * 5 / 100)\r\n" + "                    +\r\n"
			+ "                    ((SUM(grossincome) - SUM(totaldedcutions)) - 500000) * 20 / 100)\r\n"
			+ "                ELSE ((250000 * 5 / 100)\r\n" + "                    +\r\n"
			+ "                    (500000 * 20 / 100)\r\n" + "                    +\r\n"
			+ "                    ((SUM(grossincome) - SUM(totaldedcutions)) - 1000000) * 30 / 100)\r\n"
			+ "            END\r\n" + "            +\r\n" + "            ( CASE\r\n" + "\r\n"
			+ "                    WHEN (SUM(grossincome) - SUM(totaldedcutions)) <= 250000\r\n"
			+ "                    THEN 0\r\n" + "\r\n"
			+ "                    WHEN (SUM(grossincome) - SUM(totaldedcutions)) <= 500000\r\n"
			+ "                    THEN (\r\n"
			+ "                        ((SUM(grossincome) - SUM(totaldedcutions)) - 250000) * 5 / 100\r\n"
			+ "                    )\r\n" + "\r\n"
			+ "                    WHEN (SUM(grossincome) - SUM(totaldedcutions)) <= 1000000\r\n"
			+ "                    THEN (\r\n" + "                        (250000 * 5 / 100)\r\n"
			+ "                        +\r\n"
			+ "                        ((SUM(grossincome) - SUM(totaldedcutions)) - 500000) * 20 / 100\r\n"
			+ "                    )\r\n" + "\r\n" + "                    ELSE (\r\n"
			+ "                        (250000 * 5 / 100)\r\n" + "                        +\r\n"
			+ "                        (500000 * 20 / 100)\r\n" + "                        +\r\n"
			+ "                        ((SUM(grossincome) - SUM(totaldedcutions)) - 1000000) * 30 / 100\r\n"
			+ "                    )\r\n" + "\r\n" + "                END\r\n" + "            ) * 4 / 100\r\n" + "\r\n"
			+ "        ) / 12,\r\n" + "        2\r\n" + "    ) AS monthlytds\r\n" + "\r\n" + "FROM\r\n" + "(SELECT \r\n"
			+ "        SUM(amount) * 12 AS grossincome,\r\n" + "        0 AS totaldedcutions,\r\n"
			+ "        0 AS taxableincome,\r\n" + "        0 AS monthlytds\r\n" + "    FROM salarystructure\r\n"
			+ "    WHERE orgid = ?1\r\n" + "      AND branch = ?2\r\n" + "      AND employeecode = ?3\r\n"
			+ "    UNION\r\n" + "    SELECT \r\n" + "        0 AS grossincome,\r\n"
			+ "        SUM(a1.declared) AS totaldedcutions,\r\n" + "        0 AS taxableincome,\r\n"
			+ "        0 AS monthlytds\r\n" + "    FROM investmentdeclaration a\r\n"
			+ "    JOIN investmentdeclarationdetails a1\r\n"
			+ "        ON a.investmentdeclarationid = a1.investmentdeclarationid\r\n" + "    WHERE a.orgid = ?1\r\n"
			+ "      AND a.branch = ?2\r\n" + "      AND a.employeecode = ?3\r\n" + ") a")
	Set<Object[]> getDashBoardDetailsOldRegime(Long orgId, String branch, String employeeCode);
	
	@Query(nativeQuery = true, value = "WITH tax_data AS ( SELECT \r\n"
			+ "        ROUND(( CASE\r\n"
			+ "                    WHEN taxableincome <= 400000 THEN 0\r\n"
			+ "                    WHEN taxableincome <= 800000 THEN (taxableincome - 400000) * 0.05\r\n"
			+ "                    WHEN taxableincome <= 1200000 THEN 20000 + (taxableincome - 800000) * 0.10\r\n"
			+ "                    WHEN taxableincome <= 1600000 THEN 60000 + (taxableincome - 1200000) * 0.15\r\n"
			+ "                    WHEN taxableincome <= 2000000 THEN 120000 + (taxableincome - 1600000) * 0.20\r\n"
			+ "                    WHEN taxableincome <= 2400000 THEN 200000 + (taxableincome - 2000000) * 0.25\r\n"
			+ "                    ELSE 300000 + (taxableincome - 2400000) * 0.30\r\n"
			+ "                END\r\n"
			+ "            ) * 1.04,\r\n"
			+ "        2) AS yearlytds\r\n"
			+ "    FROM ( SELECT \r\n"
			+ "            (IFNULL(SUM(s.amount),0) * 12) -\r\n"
			+ "            IFNULL((\r\n"
			+ "                SELECT SUM(a1.declared)\r\n"
			+ "                FROM investmentdeclaration a\r\n"
			+ "                JOIN investmentdeclarationdetails a1\r\n"
			+ "                    ON a.investmentdeclarationid = a1.investmentdeclarationid\r\n"
			+ "                WHERE a.orgid = ?1\r\n"
			+ "                  AND a.branch = ?2\r\n"
			+ "                  AND a.employeecode = ?3\r\n"
			+ "            ),0) AS taxableincome\r\n"
			+ "        FROM salarystructure s\r\n"
			+ "        WHERE s.orgid = ?1\r\n"
			+ "          AND s.branch = ?2\r\n"
			+ "          AND s.employeecode = ?3\r\n"
			+ "    ) x\r\n"
			+ "),\r\n"
			+ "months AS (\r\n"
			+ "    SELECT 1 month_no,'April' month_name\r\n"
			+ "    UNION SELECT 2,'May'\r\n"
			+ "    UNION SELECT 3,'June'\r\n"
			+ "    UNION SELECT 4,'July'\r\n"
			+ "    UNION SELECT 5,'August'\r\n"
			+ "    UNION SELECT 6,'September'\r\n"
			+ "    UNION SELECT 7,'October'\r\n"
			+ "    UNION SELECT 8,'November'\r\n"
			+ "    UNION SELECT 9,'December'\r\n"
			+ "    UNION SELECT 10,'January'\r\n"
			+ "    UNION SELECT 11,'February'\r\n"
			+ "    UNION SELECT 12,'March' )\r\n"
			+ "SELECT \r\n"
			+ "    m.month_name,\r\n"
			+ "    CASE\r\n"
			+ "        WHEN m.month_no <= \r\n"
			+ "            CASE\r\n"
			+ "                WHEN MONTH(CURDATE()) >= 4 \r\n"
			+ "                THEN MONTH(CURDATE()) - 3\r\n"
			+ "                ELSE MONTH(CURDATE()) + 9\r\n"
			+ "            END\r\n"
			+ "        THEN ROUND(t.yearlytds / 12,2)\r\n"
			+ "        ELSE 0\r\n"
			+ "    END AS monthlytdsamount,\r\n"
			+ "    t.yearlytds\r\n"
			+ "FROM months m\r\n"
			+ "CROSS JOIN tax_data t\r\n"
			+ "ORDER BY m.month_no")
	Set<Object[]> getTdsSummaryDetails(Long orgId, String branch, String employeeCode);
	
	
	
	@Query(nativeQuery = true, value = "SELECT 1 AS sno,\r\n"
			+ "       'newRegime' AS message,\r\n"
			+ "       newRegime AS yearlyamount\r\n"
			+ "FROM\r\n"
			+ "(\r\n"
			+ "    SELECT\r\n"
			+ "        ROUND(\r\n"
			+ "            (\r\n"
			+ "                CASE\r\n"
			+ "                    WHEN taxableincome <= 400000 THEN 0\r\n"
			+ "\r\n"
			+ "                    WHEN taxableincome <= 800000\r\n"
			+ "                    THEN ((taxableincome - 400000) * 5 / 100)\r\n"
			+ "\r\n"
			+ "                    WHEN taxableincome <= 1200000\r\n"
			+ "                    THEN (\r\n"
			+ "                        400000 * 5 / 100 +\r\n"
			+ "                        ((taxableincome - 800000) * 10 / 100)\r\n"
			+ "                    )\r\n"
			+ "\r\n"
			+ "                    WHEN taxableincome <= 1600000\r\n"
			+ "                    THEN (\r\n"
			+ "                        400000 * 5 / 100 +\r\n"
			+ "                        400000 * 10 / 100 +\r\n"
			+ "                        ((taxableincome - 1200000) * 15 / 100)\r\n"
			+ "                    )\r\n"
			+ "\r\n"
			+ "                    WHEN taxableincome <= 2000000\r\n"
			+ "                    THEN (\r\n"
			+ "                        400000 * 5 / 100 +\r\n"
			+ "                        400000 * 10 / 100 +\r\n"
			+ "                        400000 * 15 / 100 +\r\n"
			+ "                        ((taxableincome - 1600000) * 20 / 100)\r\n"
			+ "                    )\r\n"
			+ "\r\n"
			+ "                    WHEN taxableincome <= 2400000\r\n"
			+ "                    THEN (\r\n"
			+ "                        400000 * 5 / 100 +\r\n"
			+ "                        400000 * 10 / 100 +\r\n"
			+ "                        400000 * 15 / 100 +\r\n"
			+ "                        400000 * 20 / 100 +\r\n"
			+ "                        ((taxableincome - 2000000) * 25 / 100)\r\n"
			+ "                    )\r\n"
			+ "\r\n"
			+ "                    ELSE (\r\n"
			+ "                        400000 * 5 / 100 +\r\n"
			+ "                        400000 * 10 / 100 +\r\n"
			+ "                        400000 * 15 / 100 +\r\n"
			+ "                        400000 * 20 / 100 +\r\n"
			+ "                        400000 * 25 / 100 +\r\n"
			+ "                        ((taxableincome - 2400000) * 30 / 100)\r\n"
			+ "                    )\r\n"
			+ "                END\r\n"
			+ "            ) * 1.04,\r\n"
			+ "            2\r\n"
			+ "        ) AS newRegime,\r\n"
			+ "\r\n"
			+ "        ROUND(\r\n"
			+ "            (\r\n"
			+ "                CASE\r\n"
			+ "                    WHEN taxableincome <= 250000 THEN 0\r\n"
			+ "\r\n"
			+ "                    WHEN taxableincome <= 500000\r\n"
			+ "                    THEN ((taxableincome - 250000) * 5 / 100)\r\n"
			+ "\r\n"
			+ "                    WHEN taxableincome <= 1000000\r\n"
			+ "                    THEN (\r\n"
			+ "                        (250000 * 5 / 100) +\r\n"
			+ "                        ((taxableincome - 500000) * 20 / 100)\r\n"
			+ "                    )\r\n"
			+ "\r\n"
			+ "                    ELSE (\r\n"
			+ "                        (250000 * 5 / 100) +\r\n"
			+ "                        (500000 * 20 / 100) +\r\n"
			+ "                        ((taxableincome - 1000000) * 30 / 100)\r\n"
			+ "                    )\r\n"
			+ "                END\r\n"
			+ "            ) * 1.04,\r\n"
			+ "            2\r\n"
			+ "        ) AS oldRegime\r\n"
			+ "\r\n"
			+ "    FROM\r\n"
			+ "    (\r\n"
			+ "        SELECT\r\n"
			+ "            SUM(grossincome) - SUM(totaldedcutions) AS taxableincome\r\n"
			+ "        FROM\r\n"
			+ "        (\r\n"
			+ "            SELECT\r\n"
			+ "                SUM(amount) * 12 AS grossincome,\r\n"
			+ "                0 AS totaldedcutions\r\n"
			+ "            FROM salarystructure\r\n"
			+ "            WHERE orgid = ?1\r\n"
			+ "              AND branch = ?2\r\n"
			+ "              AND employeecode = ?3\r\n"
			+ "\r\n"
			+ "            UNION ALL\r\n"
			+ "\r\n"
			+ "            SELECT\r\n"
			+ "                0 AS grossincome,\r\n"
			+ "                SUM(a1.declared) AS totaldedcutions\r\n"
			+ "            FROM investmentdeclaration a\r\n"
			+ "            JOIN investmentdeclarationdetails a1\r\n"
			+ "              ON a.investmentdeclarationid = a1.investmentdeclarationid\r\n"
			+ "            WHERE a.orgid = ?1\r\n"
			+ "              AND a.branch = ?2\r\n"
			+ "              AND a.employeecode = ?3\r\n"
			+ "        ) x\r\n"
			+ "    ) y\r\n"
			+ ") z\r\n"
			+ "\r\n"
			+ "UNION ALL\r\n"
			+ "\r\n"
			+ "SELECT 2 AS sno,\r\n"
			+ "       'oldRegime' AS message,\r\n"
			+ "       oldRegime AS yearlyamount\r\n"
			+ "FROM\r\n"
			+ "(\r\n"
			+ "    SELECT\r\n"
			+ "\r\n"
			+ "        ROUND(\r\n"
			+ "            (\r\n"
			+ "                CASE\r\n"
			+ "                    WHEN taxableincome <= 400000 THEN 0\r\n"
			+ "\r\n"
			+ "                    WHEN taxableincome <= 800000\r\n"
			+ "                    THEN ((taxableincome - 400000) * 5 / 100)\r\n"
			+ "\r\n"
			+ "                    WHEN taxableincome <= 1200000\r\n"
			+ "                    THEN (\r\n"
			+ "                        400000 * 5 / 100 +\r\n"
			+ "                        ((taxableincome - 800000) * 10 / 100)\r\n"
			+ "                    )\r\n"
			+ "\r\n"
			+ "                    WHEN taxableincome <= 1600000\r\n"
			+ "                    THEN (\r\n"
			+ "                        400000 * 5 / 100 +\r\n"
			+ "                        400000 * 10 / 100 +\r\n"
			+ "                        ((taxableincome - 1200000) * 15 / 100)\r\n"
			+ "                    )\r\n"
			+ "\r\n"
			+ "                    WHEN taxableincome <= 2000000\r\n"
			+ "                    THEN (\r\n"
			+ "                        400000 * 5 / 100 +\r\n"
			+ "                        400000 * 10 / 100 +\r\n"
			+ "                        400000 * 15 / 100 +\r\n"
			+ "                        ((taxableincome - 1600000) * 20 / 100)\r\n"
			+ "                    )\r\n"
			+ "\r\n"
			+ "                    WHEN taxableincome <= 2400000\r\n"
			+ "                    THEN (\r\n"
			+ "                        400000 * 5 / 100 +\r\n"
			+ "                        400000 * 10 / 100 +\r\n"
			+ "                        400000 * 15 / 100 +\r\n"
			+ "                        400000 * 20 / 100 +\r\n"
			+ "                        ((taxableincome - 2000000) * 25 / 100)\r\n"
			+ "                    )\r\n"
			+ "\r\n"
			+ "                    ELSE (\r\n"
			+ "                        400000 * 5 / 100 +\r\n"
			+ "                        400000 * 10 / 100 +\r\n"
			+ "                        400000 * 15 / 100 +\r\n"
			+ "                        400000 * 20 / 100 +\r\n"
			+ "                        400000 * 25 / 100 +\r\n"
			+ "                        ((taxableincome - 2400000) * 30 / 100)\r\n"
			+ "                    )\r\n"
			+ "                END\r\n"
			+ "            ) * 1.04,\r\n"
			+ "            2\r\n"
			+ "        ) AS newRegime,\r\n"
			+ "\r\n"
			+ "        ROUND(\r\n"
			+ "            (\r\n"
			+ "                CASE\r\n"
			+ "                    WHEN taxableincome <= 250000 THEN 0\r\n"
			+ "\r\n"
			+ "                    WHEN taxableincome <= 500000\r\n"
			+ "                    THEN ((taxableincome - 250000) * 5 / 100)\r\n"
			+ "\r\n"
			+ "                    WHEN taxableincome <= 1000000\r\n"
			+ "                    THEN (\r\n"
			+ "                        (250000 * 5 / 100) +\r\n"
			+ "                        ((taxableincome - 500000) * 20 / 100)\r\n"
			+ "                    )\r\n"
			+ "\r\n"
			+ "                    ELSE (\r\n"
			+ "                        (250000 * 5 / 100) +\r\n"
			+ "                        (500000 * 20 / 100) +\r\n"
			+ "                        ((taxableincome - 1000000) * 30 / 100)\r\n"
			+ "                    )\r\n"
			+ "                END\r\n"
			+ "            ) * 1.04,\r\n"
			+ "            2\r\n"
			+ "        ) AS oldRegime\r\n"
			+ "\r\n"
			+ "    FROM\r\n"
			+ "    (\r\n"
			+ "        SELECT\r\n"
			+ "            SUM(grossincome) - SUM(totaldedcutions) AS taxableincome\r\n"
			+ "        FROM\r\n"
			+ "        (\r\n"
			+ "            SELECT\r\n"
			+ "                SUM(amount) * 12 AS grossincome,\r\n"
			+ "                0 AS totaldedcutions\r\n"
			+ "            FROM salarystructure\r\n"
			+ "            WHERE orgid = ?1\r\n"
			+ "              AND branch = ?2\r\n"
			+ "              AND employeecode = ?3\r\n"
			+ "\r\n"
			+ "            UNION ALL\r\n"
			+ "\r\n"
			+ "            SELECT\r\n"
			+ "                0 AS grossincome,\r\n"
			+ "                SUM(a1.declared) AS totaldedcutions\r\n"
			+ "            FROM investmentdeclaration a\r\n"
			+ "            JOIN investmentdeclarationdetails a1\r\n"
			+ "              ON a.investmentdeclarationid = a1.investmentdeclarationid\r\n"
			+ "            WHERE a.orgid = ?1\r\n"
			+ "              AND a.branch = ?2\r\n"
			+ "              AND a.employeecode = ?3\r\n"
			+ "        ) x\r\n"
			+ "    ) y\r\n"
			+ ") z\r\n"
			+ "\r\n"
			+ "UNION ALL\r\n"
			+ "\r\n"
			+ "SELECT 3 AS sno,\r\n"
			+ "       'save' AS message,\r\n"
			+ "      abs( (newRegime - oldRegime)) AS yearlyamount\r\n"
			+ "FROM\r\n"
			+ "(\r\n"
			+ "    SELECT\r\n"
			+ "\r\n"
			+ "        ROUND(\r\n"
			+ "            (\r\n"
			+ "                CASE\r\n"
			+ "                    WHEN taxableincome <= 400000 THEN 0\r\n"
			+ "\r\n"
			+ "                    WHEN taxableincome <= 800000\r\n"
			+ "                    THEN ((taxableincome - 400000) * 5 / 100)\r\n"
			+ "\r\n"
			+ "                    WHEN taxableincome <= 1200000\r\n"
			+ "                    THEN (\r\n"
			+ "                        400000 * 5 / 100 +\r\n"
			+ "                        ((taxableincome - 800000) * 10 / 100)\r\n"
			+ "                    )\r\n"
			+ "\r\n"
			+ "                    WHEN taxableincome <= 1600000\r\n"
			+ "                    THEN (\r\n"
			+ "                        400000 * 5 / 100 +\r\n"
			+ "                        400000 * 10 / 100 +\r\n"
			+ "                        ((taxableincome - 1200000) * 15 / 100)\r\n"
			+ "                    )\r\n"
			+ "\r\n"
			+ "                    WHEN taxableincome <= 2000000\r\n"
			+ "                    THEN (\r\n"
			+ "                        400000 * 5 / 100 +\r\n"
			+ "                        400000 * 10 / 100 +\r\n"
			+ "                        400000 * 15 / 100 +\r\n"
			+ "                        ((taxableincome - 1600000) * 20 / 100)\r\n"
			+ "                    )\r\n"
			+ "\r\n"
			+ "                    WHEN taxableincome <= 2400000\r\n"
			+ "                    THEN (\r\n"
			+ "                        400000 * 5 / 100 +\r\n"
			+ "                        400000 * 10 / 100 +\r\n"
			+ "                        400000 * 15 / 100 +\r\n"
			+ "                        400000 * 20 / 100 +\r\n"
			+ "                        ((taxableincome - 2000000) * 25 / 100)\r\n"
			+ "                    )\r\n"
			+ "\r\n"
			+ "                    ELSE (\r\n"
			+ "                        400000 * 5 / 100 +\r\n"
			+ "                        400000 * 10 / 100 +\r\n"
			+ "                        400000 * 15 / 100 +\r\n"
			+ "                        400000 * 20 / 100 +\r\n"
			+ "                        400000 * 25 / 100 +\r\n"
			+ "                        ((taxableincome - 2400000) * 30 / 100)\r\n"
			+ "                    )\r\n"
			+ "                END\r\n"
			+ "            ) * 1.04,\r\n"
			+ "            2\r\n"
			+ "        ) AS newRegime,\r\n"
			+ "\r\n"
			+ "        ROUND(\r\n"
			+ "            (\r\n"
			+ "                CASE\r\n"
			+ "                    WHEN taxableincome <= 250000 THEN 0\r\n"
			+ "\r\n"
			+ "                    WHEN taxableincome <= 500000\r\n"
			+ "                    THEN ((taxableincome - 250000) * 5 / 100)\r\n"
			+ "\r\n"
			+ "                    WHEN taxableincome <= 1000000\r\n"
			+ "                    THEN (\r\n"
			+ "                        (250000 * 5 / 100) +\r\n"
			+ "                        ((taxableincome - 500000) * 20 / 100)\r\n"
			+ "                    )\r\n"
			+ "\r\n"
			+ "                    ELSE (\r\n"
			+ "                        (250000 * 5 / 100) +\r\n"
			+ "                        (500000 * 20 / 100) +\r\n"
			+ "                        ((taxableincome - 1000000) * 30 / 100)\r\n"
			+ "                    )\r\n"
			+ "                END\r\n"
			+ "            ) * 1.04,\r\n"
			+ "            2\r\n"
			+ "        ) AS oldRegime\r\n"
			+ "\r\n"
			+ "    FROM\r\n"
			+ "    (\r\n"
			+ "        SELECT\r\n"
			+ "            SUM(grossincome) - SUM(totaldedcutions) AS taxableincome\r\n"
			+ "        FROM\r\n"
			+ "        (\r\n"
			+ "            SELECT\r\n"
			+ "                SUM(amount) * 12 AS grossincome,\r\n"
			+ "                0 AS totaldedcutions\r\n"
			+ "            FROM salarystructure\r\n"
			+ "            WHERE orgid = ?1\r\n"
			+ "              AND branch = ?2\r\n"
			+ "              AND employeecode = ?3\r\n"
			+ "\r\n"
			+ "            UNION ALL\r\n"
			+ "\r\n"
			+ "            SELECT\r\n"
			+ "                0 AS grossincome,\r\n"
			+ "                SUM(a1.declared) AS totaldedcutions\r\n"
			+ "            FROM investmentdeclaration a\r\n"
			+ "            JOIN investmentdeclarationdetails a1\r\n"
			+ "              ON a.investmentdeclarationid = a1.investmentdeclarationid\r\n"
			+ "            WHERE a.orgid = ?1\r\n"
			+ "              AND a.branch = ?2\r\n"
			+ "              AND a.employeecode = ?3\r\n"
			+ "        ) x\r\n"
			+ "    ) y\r\n"
			+ ") z")
	Set<Object[]> getTaxRegimeComparisonDetails(Long orgId, String branch, String employeeCode);

	InvestmentDeclarationVO findByOrgIdAndIdAndEmployeeCode(Long orgId, Long id, String employeeCode);

}
