package com.efit.hrms.repo;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.efit.hrms.entity.OtCalculationVO;

@Repository
public interface OtCalculationRepo extends JpaRepository<OtCalculationVO, Long>{

	
	
	//BEFORE SEP 9
//	@Query(
//		    value = "WITH company_cte AS (\r\n"
//		    		+ "    SELECT * FROM company WHERE companyid = ?1\r\n"
//		    		+ "),\r\n"
//		    		+ "shift_cte AS (\r\n"
//		    		+ "    SELECT \r\n"
//		    		+ "    sd.employeecode,\r\n"
//		    		+ "    CASE\r\n"
//		    		+ "        -- Night shift: OUT time < IN time\r\n"
//		    		+ "        WHEN sd.outtime < sd.intime THEN\r\n"
//		    		+ "            TIME_TO_SEC(TIMEDIFF(ADDTIME(sd.outtime, '24:00:00'), sd.intime))\r\n"
//		    		+ "        ELSE\r\n"
//		    		+ "            TIME_TO_SEC(TIMEDIFF(sd.outtime, sd.intime))\r\n"
//		    		+ "    END AS working_sec,\r\n"
//		    		+ "    sd.effectivefrom,\r\n"
//		    		+ "    sd.effectiveto\r\n"
//		    		+ "FROM \r\n"
//		    		+ "    shiftassigndetails sd\r\n"
//		    		+ "JOIN \r\n"
//		    		+ "    shiftassign sa ON sd.shiftassignid = sa.shiftassignid\r\n"
//		    		+ "WHERE \r\n"
//		    		+ "    sa.orgid = ?1 \r\n"
//		    		+ "    AND sd.active = 1\r\n"
//		    		+ "),\r\n"
//		    		+ "salary_cte AS (\r\n"
//		    		+ "    SELECT employeecode, amount AS monthly_salary\r\n"
//		    		+ "    FROM (\r\n"
//		    		+ "        SELECT ss.employeecode,\r\n"
//		    		+ "               ss.amount,\r\n"
//		    		+ "               ROW_NUMBER() OVER (PARTITION BY ss.employeecode ORDER BY ss.createdon DESC) AS rn\r\n"
//		    		+ "        FROM salarystructure ss\r\n"
//		    		+ "        WHERE ss.orgid = ?1 AND ss.active = 1\r\n"
//		    		+ "    ) t\r\n"
//		    		+ "    WHERE t.rn = 1\r\n"
//		    		+ "),\r\n"
//		    		+ "attendance_cte AS (\r\n"
//		    		+ "    SELECT ad.empcode, ad.empname, ad.branch, ad.branchcode, ad.checkindate,\r\n"
//		    		+ "           ad.intime, ad.outtime, ad.grosshours AS work_hrs\r\n"
//		    		+ "    FROM attendancedaily ad\r\n"
//		    		+ "    JOIN company_cte c ON ad.orgid = c.companyid\r\n"
//		    		+ "    JOIN employee e ON ad.empcode = e.employeecode\r\n"
//		    		+ "    WHERE ad.orgid = ?1\r\n"
//		    		+ "      AND FIND_IN_SET(ad.attendancemode, c.attendancemode)\r\n"
//		    		+ "      AND c.otflag = 1\r\n"
//		    		+ "      AND e.otflag = 1\r\n"
//		    		+ "      AND (\r\n"
//		    		+ "          c.ottype = 'ALL' OR\r\n"
//		    		+ "          (c.ottype = 'EMPLOYEE' AND LOWER(e.type) = 'employee') OR\r\n"
//		    		+ "          (c.ottype = 'CONTRACTOR' AND LOWER(e.type) = 'contractor')\r\n"
//		    		+ "      )\r\n"
//		    		+ "     AND ad.checkindate \r\n"
//		    		+ "    BETWEEN DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 MONTH), '%Y-%m-01')\r\n"
//		    		+ "    AND CURDATE()"
//		    		+ "\r\n"
//		    		+ "),\r\n"
//		    		+ "daytype_cte AS (\r\n"
//		    		+ "    SELECT ds.empcode, ds.checkindate,\r\n"
//		    		+ "           CASE\r\n"
//		    		+ "               WHEN h.holidaydate IS NOT NULL THEN 'Holiday'\r\n"
//		    		+ "               WHEN EXISTS (\r\n"
//		    		+ "                   SELECT 1 FROM companyweekoff cw\r\n"
//		    		+ "                   WHERE cw.companyid = ?1 AND UPPER(cw.weekoffdays) = UPPER(DAYNAME(ds.checkindate))\r\n"
//		    		+ "               ) THEN 'Weekly-Off'\r\n"
//		    		+ "               ELSE 'Regular'\r\n"
//		    		+ "           END AS daytype\r\n"
//		    		+ "    FROM attendance_cte ds\r\n"
//		    		+ "    LEFT JOIN holidays h ON h.orgid = ?1 AND h.holidaydate = ds.checkindate\r\n"
//		    		+ "),\r\n"
//		    		+ "ot_policy_cte AS (\r\n"
//		    		+ "    SELECT om.otmasterid, om.otcategory, om.ottype,\r\n"
//		    		+ "           omd.minhours * 3600 AS min_sec,\r\n"
//		    		+ "           omd.maxhours * 3600 AS max_sec,\r\n"
//		    		+ "           omd.otrate, omd.slab, omd.effectivefrom, omd.effectiveto\r\n"
//		    		+ "    FROM otmaster om\r\n"
//		    		+ "    JOIN otmasterdetails omd ON omd.otmasterid = om.otmasterid\r\n"
//		    		+ "    WHERE om.orgid = ?1\r\n"
//		    		+ "      AND om.active = 1\r\n"
//		    		+ "      AND omd.applicable = 1\r\n"
//		    		+ "      AND om.ottype = (SELECT otpolicy FROM company WHERE companyid = ?1)\r\n"
//		    		+ "),\r\n"
//		    		+ "combined_cte AS (\r\n"
//		    		+ "    SELECT a.empcode, a.empname, a.branch, a.branchcode, a.checkindate,\r\n"
//		    		+ "           STR_TO_DATE(a.intime, '%H:%i:%s') AS intime,\r\n"
//		    		+ "           STR_TO_DATE(a.outtime, '%H:%i:%s') AS outtime,\r\n"
//		    		+ "           a.work_hrs * 3600 AS work_sec,\r\n"
//		    		+ "           sft.working_sec, d.daytype\r\n"
//		    		+ "    FROM attendance_cte a\r\n"
//		    		+ "    LEFT JOIN shift_cte sft ON sft.employeecode = a.empcode\r\n"
//		    		+ "        AND a.checkindate BETWEEN sft.effectivefrom AND sft.effectiveto\r\n"
//		    		+ "    JOIN daytype_cte d ON d.empcode = a.empcode AND d.checkindate = a.checkindate\r\n"
//		    		+ "),\r\n"
//		    		+ "ot_calc_cte AS (\r\n"
//		    		+ "    SELECT c.*, COALESCE(c.work_sec - COALESCE(c.working_sec, 0), 0) AS raw_ot_sec\r\n"
//		    		+ "    FROM combined_cte c\r\n"
//		    		+ "),\r\n"
//		    		+ "ot_filtered_ranked_cte AS (\r\n"
//		    		+ "    SELECT o.*, p.otcategory, p.ottype, p.min_sec, p.max_sec, p.otrate, p.slab,\r\n"
//		    		+ "           ROW_NUMBER() OVER (\r\n"
//		    		+ "             PARTITION BY o.empcode, o.checkindate\r\n"
//		    		+ "             ORDER BY p.min_sec DESC\r\n"
//		    		+ "           ) AS rn\r\n"
//		    		+ "    FROM ot_calc_cte o\r\n"
//		    		+ "    JOIN ot_policy_cte p \r\n"
//		    		+ "      ON p.otcategory = o.daytype\r\n"
//		    		+ "     AND o.checkindate BETWEEN p.effectivefrom AND p.effectiveto\r\n"
//		    		+ "     AND o.raw_ot_sec BETWEEN p.min_sec AND p.max_sec\r\n"
//		    		+ "),\r\n"
//		    		+ "company_ot_policy AS (\r\n"
//		    		+ "    SELECT companyid, otpolicy FROM company WHERE companyid = ?1\r\n"
//		    		+ "),\r\n"
//		    		+ "calendar_days_cte AS (\r\n"
//		    		+ "    SELECT e.employeecode AS empcode,\r\n"
//		    		+ "           DAY(LAST_DAY(CURDATE())) AS total_days_in_month\r\n"
//		    		+ "    FROM employee e\r\n"
//		    		+ "    WHERE e.orgid = ?1\r\n"
//		    		+ ")\r\n"
//		    		+ "\r\n"
//		    		+ "SELECT fr.empcode, fr.empname, fr.checkindate,\r\n"
//		    		+ "       TIME_FORMAT(fr.intime, '%H:%i:%s') AS intime,\r\n"
//		    		+ "       TIME_FORMAT(fr.outtime, '%H:%i:%s') AS outtime,\r\n"
//		    		+ "\r\n"
//		    		+ "       FLOOR(fr.raw_ot_sec / 3600) AS othours,\r\n"
//		    		+ "\r\n"
//		    		+ "       CASE \r\n"
//		    		+ "           WHEN cp.otpolicy = 'Hourly' THEN\r\n"
//		    		+ "               FLOOR(\r\n"
//		    		+ "                   FLOOR(fr.raw_ot_sec / 3600) * \r\n"
//		    		+ "                   (\r\n"
//		    		+ "                       s.monthly_salary / cd.total_days_in_month / \r\n"
//		    		+ "                       (fr.working_sec / 3600)\r\n"
//		    		+ "                   )\r\n"
//		    		+ "               )\r\n"
//		    		+ "           WHEN cp.otpolicy = 'Slab' THEN\r\n"
//		    		+ "               FLOOR(\r\n"
//		    		+ "                   (s.monthly_salary / cd.total_days_in_month) * (fr.otrate / 100)\r\n"
//		    		+ "               )\r\n"
//		    		+ "           ELSE 0\r\n"
//		    		+ "       END AS otamount,\r\n"
//		    		+ "\r\n"
//		    		+ "       CASE \r\n"
//		    		+ "           WHEN cp.otpolicy = 'Hourly' THEN '0'\r\n"
//		    		+ "           ELSE fr.otrate\r\n"
//		    		+ "       END AS rate,\r\n"
//		    		+ "       \r\n"
//		    		+ "       fr.ottype,\r\n"
//		    		+ "       fr.otcategory,\r\n"
//		    		+ "       cp.otpolicy AS companyotpolicy\r\n"
//		    		+ "\r\n"
//		    		+ "FROM ot_filtered_ranked_cte fr\r\n"
//		    		+ "JOIN company_ot_policy cp ON cp.companyid = ?1\r\n"
//		    		+ "JOIN salary_cte s ON s.employeecode = fr.empcode\r\n"
//		    		+ "JOIN calendar_days_cte cd ON cd.empcode = fr.empcode\r\n"
//		    		+ "LEFT JOIN otcalculation otc\r\n"
//		    		+ "  ON otc.empcode = fr.empcode\r\n"
//		    		+ " AND otc.checkindate = fr.checkindate\r\n"
//		    		+ "WHERE fr.rn = 1\r\n"
//		    		+ "  AND (otc.status = 'PENDING' OR otc.status IS NULL OR otc.empcode IS NULL)\r\n"
//		    		+ "ORDER BY fr.checkindate, fr.empcode\r\n"
//		    		+ "\r\n"
//		    		+ "",
//		    nativeQuery = true
//		)
//		List<Object[]> getFinalOtRecords(Long orgId);

		
//		sep 10 correct but with slab,hourly in open shift
//	@Query(
//		    value = "WITH company_cte AS (\r\n"
//		    		+ "    SELECT * FROM company WHERE companyid = ?1\r\n"
//		    		+ "),\r\n"
//		    		+ "shift_cte AS (\r\n"
//		    		+ "    SELECT sd.employeecode,\r\n"
//		    		+ "           CASE \r\n"
//		    		+ "               WHEN sd.outtime < sd.intime \r\n"
//		    		+ "                    THEN TIME_TO_SEC(TIMEDIFF(ADDTIME(sd.outtime, '24:00:00'), sd.intime))\r\n"
//		    		+ "               ELSE TIME_TO_SEC(TIMEDIFF(sd.outtime, sd.intime)) \r\n"
//		    		+ "           END AS working_sec,\r\n"
//		    		+ "           sd.effectivefrom, sd.effectiveto\r\n"
//		    		+ "    FROM shiftassigndetails sd\r\n"
//		    		+ "    JOIN shiftassign sa ON sd.shiftassignid = sa.shiftassignid\r\n"
//		    		+ "    WHERE sa.orgid = ?1 AND sd.active = 1\r\n"
//		    		+ "),\r\n"
//		    		+ "salary_cte AS (\r\n"
//		    		+ "    SELECT employeecode, sumofearning\r\n"
//		    		+ "    FROM (\r\n"
//		    		+ "        SELECT ss.employeecode, ss.sumofearning,\r\n"
//		    		+ "               ROW_NUMBER() OVER (\r\n"
//		    		+ "                   PARTITION BY ss.employeecode \r\n"
//		    		+ "                   ORDER BY STR_TO_DATE(ss.createdon, '%d-%m-%Y %h:%i:%s %p') DESC\r\n"
//		    		+ "               ) AS rn\r\n"
//		    		+ "        FROM salarystructure ss \r\n"
//		    		+ "        WHERE ss.orgid = ?1 AND ss.active = 1\r\n"
//		    		+ "    ) t \r\n"
//		    		+ "    WHERE t.rn = 1\r\n"
//		    		+ "),\r\n"
//		    		+ "attendance_cte AS (\r\n"
//		    		+ "    SELECT ad.empcode, ad.empname, ad.branch, ad.branchcode, ad.checkindate,\r\n"
//		    		+ "           ad.intime, ad.outtime, ad.grosshours AS work_hrs\r\n"
//		    		+ "    FROM attendancedaily ad\r\n"
//		    		+ "    JOIN company_cte c ON ad.orgid = c.companyid\r\n"
//		    		+ "    JOIN employee e ON ad.empcode = e.employeecode\r\n"
//		    		+ "    WHERE ad.orgid = ?1\r\n"
//		    		+ "      AND FIND_IN_SET(ad.attendancemode, c.attendancemode)\r\n"
//		    		+ "      AND c.otflag = 1\r\n"
//		    		+ "      AND e.otflag = 1\r\n"
//		    		+ "      AND (c.ottype = 'ALL' \r\n"
//		    		+ "           OR (c.ottype = 'EMPLOYEE' AND LOWER(e.type) = 'employee') \r\n"
//		    		+ "           OR (c.ottype = 'CONTRACTOR' AND LOWER(e.type) = 'contractor'))\r\n"
//		    		+ "      AND ad.checkindate BETWEEN '2025-07-01' AND '2025-07-31'\r\n"
//		    		+ "),\r\n"
//		    		+ "daytype_cte AS (\r\n"
//		    		+ "    SELECT ds.empcode, ds.checkindate,\r\n"
//		    		+ "           CASE \r\n"
//		    		+ "               WHEN h.holidaydate IS NOT NULL THEN 'Holiday'\r\n"
//		    		+ "               WHEN EXISTS (\r\n"
//		    		+ "                    SELECT 1 FROM companyweekoff cw \r\n"
//		    		+ "                    WHERE cw.companyid = ?1\r\n"
//		    		+ "                      AND UPPER(cw.weekoffdays) = UPPER(DAYNAME(ds.checkindate))\r\n"
//		    		+ "               ) THEN 'Weekly-Off'\r\n"
//		    		+ "               ELSE 'Regular' \r\n"
//		    		+ "           END AS daytype\r\n"
//		    		+ "    FROM attendance_cte ds\r\n"
//		    		+ "    LEFT JOIN holidays h ON h.orgid = ?1 AND h.holidaydate = ds.checkindate\r\n"
//		    		+ "),\r\n"
//		    		+ "ot_policy_cte AS (\r\n"
//		    		+ "    SELECT om.otmasterid, om.otcategory, om.ottype, \r\n"
//		    		+ "           omd.minhours * 3600 AS min_sec,\r\n"
//		    		+ "           omd.maxhours * 3600 AS max_sec, \r\n"
//		    		+ "           omd.otrate, omd.slab, \r\n"
//		    		+ "           omd.effectivefrom, omd.effectiveto\r\n"
//		    		+ "    FROM otmaster om\r\n"
//		    		+ "    JOIN otmasterdetails omd ON omd.otmasterid = om.otmasterid\r\n"
//		    		+ "    WHERE om.orgid = ?1 \r\n"
//		    		+ "      AND om.active = 1 \r\n"
//		    		+ "      AND omd.applicable = 1\r\n"
//		    		+ "      AND UPPER(om.ottype) = 'SLAB'\r\n"
//		    		+ "),\r\n"
//		    		+ "combined_cte AS (\r\n"
//		    		+ "    SELECT a.empcode, a.empname, a.branch, a.branchcode, a.checkindate,\r\n"
//		    		+ "           STR_TO_DATE(a.intime, '%H:%i:%s') AS intime,\r\n"
//		    		+ "           STR_TO_DATE(a.outtime, '%H:%i:%s') AS outtime,\r\n"
//		    		+ "           a.work_hrs * 3600 AS work_sec,\r\n"
//		    		+ "           COALESCE(sft.working_sec, 0) AS working_sec,\r\n"
//		    		+ "           d.daytype\r\n"
//		    		+ "    FROM attendance_cte a\r\n"
//		    		+ "    LEFT JOIN shift_cte sft \r\n"
//		    		+ "           ON sft.employeecode = a.empcode \r\n"
//		    		+ "          AND a.checkindate BETWEEN sft.effectivefrom AND sft.effectiveto\r\n"
//		    		+ "    JOIN daytype_cte d \r\n"
//		    		+ "           ON d.empcode = a.empcode \r\n"
//		    		+ "          AND d.checkindate = a.checkindate\r\n"
//		    		+ "),\r\n"
//		    		+ "ot_calc_cte AS (\r\n"
//		    		+ "    SELECT c.*, \r\n"
//		    		+ "           COALESCE(c.work_sec - COALESCE(c.working_sec, 0), 0) AS raw_ot_sec\r\n"
//		    		+ "    FROM combined_cte c\r\n"
//		    		+ "),\r\n"
//		    		+ "company_ot_policy AS (\r\n"
//		    		+ "    SELECT companyid, otpolicy, oteligiblehours,shifthours \r\n"
//		    		+ "    FROM company \r\n"
//		    		+ "    WHERE companyid = ?1\r\n"
//		    		+ ")\r\n"
//		    		+ "SELECT *\r\n"
//		    		+ "FROM (\r\n"
//		    		+ "    SELECT fr.empcode, fr.empname, fr.checkindate,\r\n"
//		    		+ "           TIME_FORMAT(fr.intime, '%H:%i:%s') AS intime,\r\n"
//		    		+ "           TIME_FORMAT(fr.outtime, '%H:%i:%s') AS outtime,"
//		    		+ "CAST(\r\n"
//		    		+ "    CASE\r\n"
//		    		+ "        WHEN UPPER(cp.otpolicy) = 'OTHERS'\r\n"
//		    		+ "             THEN GREATEST(0, FLOOR(fr.work_sec / 3600) - cp.shifthours)\r\n"
//		    		+ "        ELSE FLOOR(fr.raw_ot_sec / 3600)\r\n"
//		    		+ "    END AS SIGNED\r\n"
//		    		+ ") AS othours,\r\n"
//		    		+ "           CASE\r\n"
//		    		+ "               WHEN UPPER(cp.otpolicy) = 'HOURLY' THEN \r\n"
//		    		+ "                    FLOOR(FLOOR(fr.raw_ot_sec / 3600) * (s.sumofearning / 30 / (fr.working_sec / 3600)))\r\n"
//		    		+ "               WHEN UPPER(cp.otpolicy) = 'SLAB' AND op.otrate IS NOT NULL THEN\r\n"
//		    		+ "                    FLOOR((s.sumofearning / 30) * (op.otrate / 100))\r\n"
//		    		+ "               WHEN UPPER(cp.otpolicy) = 'OTHERS' \r\n"
//		    		+ "                    AND (fr.work_sec / 3600) >= (cp.shifthours + cp.oteligiblehours) THEN \r\n"
//		    		+ "                    FLOOR(s.sumofearning / 30)\r\n"
//		    		+ "               ELSE 0\r\n"
//		    		+ "           END AS otamount,\r\n"
//		    		+ "           CASE \r\n"
//		    		+ "    WHEN cp.otpolicy = 'SLAB' THEN COALESCE(op.otrate, 0) \r\n"
//		    		+ "    ELSE 0 \r\n"
//		    		+ "END AS rate\r\n"
//		    		+ ",     -- ✅ 7th column\r\n"
//		    		+ "           cp.otpolicy AS ottype,              -- ✅ 8th column\r\n"
//		    		+ "           CASE \r\n"
//		    		+ "               WHEN UPPER(cp.otpolicy) = 'SLAB' THEN UPPER(op.otcategory) \r\n"
//		    		+ "               WHEN UPPER(cp.otpolicy) = 'HOURLY' THEN 'HOURLY'\r\n"
//		    		+ "               ELSE 'OTHERS' \r\n"
//		    		+ "           END AS otcategory,                  -- ✅ 9th column\r\n"
//		    		+ "           cp.otpolicy AS companyotpolicy      -- ✅ 10th column\r\n"
//		    		+ "    FROM ot_calc_cte fr\r\n"
//		    		+ "    JOIN company_ot_policy cp ON cp.companyid = ?1\r\n"
//		    		+ "    JOIN salary_cte s ON s.employeecode = fr.empcode\r\n"
//		    		+ "    LEFT JOIN ot_policy_cte op \r\n"
//		    		+ "           ON op.otcategory = fr.daytype\r\n"
//		    		+ "          AND fr.raw_ot_sec BETWEEN op.min_sec AND op.max_sec\r\n"
//		    		+ "          AND fr.checkindate BETWEEN op.effectivefrom AND op.effectiveto\r\n"
//		    		+ "    WHERE (\r\n"
//		    		+ "            (UPPER(cp.otpolicy) = 'HOURLY' AND fr.raw_ot_sec > 0)\r\n"
//		    		+ "         OR (UPPER(cp.otpolicy) = 'SLAB' AND op.otrate IS NOT NULL)\r\n"
//		    		+ "         OR (UPPER(cp.otpolicy) = 'OTHERS' AND (fr.work_sec / 3600) >= (cp.shifthours + cp.oteligiblehours))\r\n"
//		    		+ "    )\r\n"
//		    		+ ") final\r\n"
//		    		+ "WHERE final.otamount > 0\r\n"
//		    		+ "ORDER BY checkindate, empcode \r\n"
//		    		+ " \r\n"
//		    		+ "",
//		    nativeQuery = true
//		)
//		List<Object[]> getFinalOtRecords(Long orgId);

// 22-09-2025 currect but only one amount	
//	//not allow slab/hourly in open shift - sep 12
//	@Query(
//		    value = "WITH company_cte AS (\r\n"
//		    		+ "    SELECT * FROM company WHERE companyid = ?1\r\n"
//		    		+ "),\r\n"
//		    		+ "shift_cte AS (\r\n"
//		    		+ "    SELECT sd.employeecode,\r\n"
//		    		+ "           sd.shifttype,\r\n"
//		    		+ "           CASE \r\n"
//		    		+ "               WHEN sd.outtime < sd.intime \r\n"
//		    		+ "                    THEN TIME_TO_SEC(TIMEDIFF(ADDTIME(sd.outtime, '24:00:00'), sd.intime))\r\n"
//		    		+ "               ELSE TIME_TO_SEC(TIMEDIFF(sd.outtime, sd.intime)) \r\n"
//		    		+ "           END AS working_sec,\r\n"
//		    		+ "           sd.effectivefrom, sd.effectiveto\r\n"
//		    		+ "    FROM shiftassigndetails sd\r\n"
//		    		+ "    JOIN shiftassign sa ON sd.shiftassignid = sa.shiftassignid\r\n"
//		    		+ "    WHERE sa.orgid = ?1 AND sd.active = 1\r\n"
//		    		+ "),\r\n"
//		    		+ "salary_cte AS (\r\n"
//		    		+ "    SELECT employeecode, sumofearning\r\n"
//		    		+ "    FROM (\r\n"
//		    		+ "        SELECT ss.employeecode, ss.sumofearning,\r\n"
//		    		+ "               ROW_NUMBER() OVER (\r\n"
//		    		+ "                   PARTITION BY ss.employeecode \r\n"
//		    		+ "                   ORDER BY STR_TO_DATE(ss.createdon, '%d-%m-%Y %h:%i:%s %p') DESC\r\n"
//		    		+ "               ) AS rn\r\n"
//		    		+ "        FROM salarystructure ss \r\n"
//		    		+ "        WHERE ss.orgid = ?1 AND ss.active = 1\r\n"
//		    		+ "    ) t \r\n"
//		    		+ "    WHERE t.rn = 1\r\n"
//		    		+ "),\r\n"
//		    		+ "attendance_cte AS (\r\n"
//		    		+ "    SELECT ad.empcode, ad.empname, ad.branch, ad.branchcode, ad.checkindate,\r\n"
//		    		+ "           ad.intime, ad.outtime, ad.effectivehours AS work_hrs\r\n"
//		    		+ "    FROM attendancedaily ad\r\n"
//		    		+ "    JOIN company_cte c ON ad.orgid = c.companyid\r\n"
//		    		+ "    JOIN employee e ON ad.empcode = e.employeecode\r\n"
//		    		+ "    WHERE ad.orgid = ?1\r\n"
//		    		+ "      AND FIND_IN_SET(ad.attendancemode, c.attendancemode)\r\n"
//		    		+ "      AND c.otflag = 1\r\n"
//		    		+ "      AND e.otflag = 1\r\n"
//		    		+ "      AND (c.ottype = 'ALL' \r\n"
//		    		+ "           OR (c.ottype = 'EMPLOYEE' AND LOWER(e.type) = 'employee') \r\n"
//		    		+ "           OR (c.ottype = 'CONTRACTOR' AND LOWER(e.type) = 'contractor'))\r\n"
//		    		+ "      AND ad.checkindate BETWEEN '2025-07-01' AND '2025-07-31'\r\n"
//		    		+ "),\r\n"
//		    		+ "daytype_cte AS (\r\n"
//		    		+ "    SELECT ds.empcode, ds.checkindate,\r\n"
//		    		+ "           CASE \r\n"
//		    		+ "               WHEN h.holidaydate IS NOT NULL THEN 'Holiday'\r\n"
//		    		+ "               WHEN EXISTS (\r\n"
//		    		+ "                    SELECT 1 FROM companyweekoff cw \r\n"
//		    		+ "                    WHERE cw.companyid = ?1\r\n"
//		    		+ "                      AND UPPER(cw.weekoffdays) = UPPER(DAYNAME(ds.checkindate))\r\n"
//		    		+ "               ) THEN 'Weekly-Off'\r\n"
//		    		+ "               ELSE 'Regular' \r\n"
//		    		+ "           END AS daytype\r\n"
//		    		+ "    FROM attendance_cte ds\r\n"
//		    		+ "    LEFT JOIN holidays h ON h.orgid = ?1 AND h.holidaydate = ds.checkindate\r\n"
//		    		+ "),\r\n"
//		    		+ "ot_policy_cte AS (\r\n"
//		    		+ "    SELECT om.otmasterid, om.otcategory, om.ottype, \r\n"
//		    		+ "           omd.minhours * 3600 AS min_sec,\r\n"
//		    		+ "           omd.maxhours * 3600 AS max_sec, \r\n"
//		    		+ "           omd.otrate, omd.slab, \r\n"
//		    		+ "           omd.effectivefrom, omd.effectiveto\r\n"
//		    		+ "    FROM otmaster om\r\n"
//		    		+ "    JOIN otmasterdetails omd ON omd.otmasterid = om.otmasterid\r\n"
//		    		+ "    WHERE om.orgid = ?1 \r\n"
//		    		+ "      AND om.active = 1 \r\n"
//		    		+ "      AND omd.applicable = 1\r\n"
//		    		+ "      AND UPPER(om.ottype) = 'SLAB'\r\n"
//		    		+ "),\r\n"
//		    		+ "combined_cte AS (\r\n"
//		    		+ "    SELECT a.empcode, a.empname, a.branch, a.branchcode, a.checkindate,\r\n"
//		    		+ "           STR_TO_DATE(a.intime, '%H:%i:%s') AS intime,\r\n"
//		    		+ "           STR_TO_DATE(a.outtime, '%H:%i:%s') AS outtime,\r\n"
//		    		+ "           a.work_hrs * 3600 AS work_sec,\r\n"
//		    		+ "           COALESCE(sft.working_sec, 0) AS working_sec,\r\n"
//		    		+ "           sft.shifttype,\r\n"
//		    		+ "           d.daytype\r\n"
//		    		+ "    FROM attendance_cte a\r\n"
//		    		+ "    LEFT JOIN shift_cte sft \r\n"
//		    		+ "           ON sft.employeecode = a.empcode \r\n"
//		    		+ "          AND a.checkindate BETWEEN sft.effectivefrom AND sft.effectiveto\r\n"
//		    		+ "    JOIN daytype_cte d \r\n"
//		    		+ "           ON d.empcode = a.empcode \r\n"
//		    		+ "          AND d.checkindate = a.checkindate\r\n"
//		    		+ "),\r\n"
//		    		+ "ot_calc_cte AS (\r\n"
//		    		+ "    SELECT c.*, \r\n"
//		    		+ "           COALESCE(c.work_sec - COALESCE(c.working_sec, 0), 0) AS raw_ot_sec\r\n"
//		    		+ "    FROM combined_cte c\r\n"
//		    		+ "),\r\n"
//		    		+ "company_ot_policy AS (\r\n"
//		    		+ "    SELECT companyid, otpolicy, oteligiblehours, shifthours \r\n"
//		    		+ "    FROM company \r\n"
//		    		+ "    WHERE companyid = ?1\r\n"
//		    		+ ")\r\n"
//		    		+ "SELECT *\r\n"
//		    		+ "FROM (\r\n"
//		    		+ "    SELECT fr.empcode, fr.empname, fr.checkindate,\r\n"
//		    		+ "           TIME_FORMAT(fr.intime, '%H:%i:%s') AS intime,\r\n"
//		    		+ "           TIME_FORMAT(fr.outtime, '%H:%i:%s') AS outtime,\r\n"
//		    		+ "\r\n"
//		    		+ "           CAST(\r\n"
//		    		+ "               CASE\r\n"
//		    		+ "                   WHEN (UPPER(cp.otpolicy) = 'OTHERS' AND fr.shifttype = 'OPEN')\r\n"
//		    		+ "                        THEN GREATEST(0, FLOOR(fr.work_sec / 3600) - cp.shifthours)\r\n"
//		    		+ "                   ELSE FLOOR(fr.raw_ot_sec / 3600)\r\n"
//		    		+ "               END AS SIGNED\r\n"
//		    		+ "           ) AS othours,\r\n"
//		    		+ "\r\n"
//		    		+ "          CASE\r\n"
//		    		+ "    WHEN (UPPER(cp.otpolicy) = 'HOURLY' AND fr.shifttype <> 'OPEN') THEN \r\n"
//		    		+ "         ROUND((fr.raw_ot_sec / 3600) * (s.sumofearning / 30 / (fr.working_sec / 3600)), 2)\r\n"
//		    		+ "    WHEN (UPPER(cp.otpolicy) = 'SLAB' AND fr.shifttype <> 'OPEN' AND op.otrate IS NOT NULL) THEN\r\n"
//		    		+ "         ROUND((s.sumofearning / 30) * (op.otrate / 100), 2)\r\n"
//		    		+ "    WHEN (UPPER(cp.otpolicy) = 'OTHERS' AND fr.shifttype = 'OPEN'\r\n"
//		    		+ "          AND (fr.work_sec / 3600) >= (cp.shifthours + cp.oteligiblehours)) THEN \r\n"
//		    		+ "         ROUND(s.sumofearning / 30, 2)\r\n"
//		    		+ "    ELSE 0\r\n"
//		    		+ "END AS otamount,\r\n"
//		    		+ "\r\n"
//		    		+ "\r\n"
//		    		+ "           CASE \r\n"
//		    		+ "               WHEN cp.otpolicy = 'SLAB' THEN COALESCE(op.otrate, 0) \r\n"
//		    		+ "               ELSE 0 \r\n"
//		    		+ "           END AS rate,\r\n"
//		    		+ "\r\n"
//		    		+ "           cp.otpolicy AS ottype,\r\n"
//		    		+ "           CASE \r\n"
//		    		+ "               WHEN UPPER(cp.otpolicy) = 'SLAB' THEN UPPER(op.otcategory) \r\n"
//		    		+ "               WHEN UPPER(cp.otpolicy) = 'HOURLY' THEN 'HOURLY'\r\n"
//		    		+ "               ELSE 'OTHERS' \r\n"
//		    		+ "           END AS otcategory,\r\n"
//		    		+ "           cp.otpolicy AS companyotpolicy,\r\n"
//		    		+ "           otc.status AS otstatus\r\n"
//		    		+ "    FROM ot_calc_cte fr\r\n"
//		    		+ "    JOIN company_ot_policy cp ON cp.companyid = ?1\r\n"
//		    		+ "    JOIN salary_cte s ON s.employeecode = fr.empcode\r\n"
//		    		+ "    LEFT JOIN ot_policy_cte op \r\n"
//		    		+ "           ON op.otcategory = fr.daytype\r\n"
//		    		+ "          AND fr.raw_ot_sec BETWEEN op.min_sec AND op.max_sec\r\n"
//		    		+ "          AND fr.checkindate BETWEEN op.effectivefrom AND op.effectiveto\r\n"
//		    		+ "    LEFT JOIN otcalculation otc \r\n"
//		    		+ "           ON otc.empcode = fr.empcode\r\n"
//		    		+ "          AND otc.checkindate = fr.checkindate\r\n"
//		    		+ "    WHERE (\r\n"
//		    		+ "            (UPPER(cp.otpolicy) = 'HOURLY' AND fr.shifttype <> 'OPEN' AND fr.raw_ot_sec > 0)\r\n"
//		    		+ "         OR (UPPER(cp.otpolicy) = 'SLAB' AND fr.shifttype <> 'OPEN' AND op.otrate IS NOT NULL)\r\n"
//		    		+ "         OR (UPPER(cp.otpolicy) = 'OTHERS' AND fr.shifttype = 'OPEN'\r\n"
//		    		+ "             AND (fr.work_sec / 3600) >= (cp.shifthours + cp.oteligiblehours))\r\n"
//		    		+ "    )\r\n"
//		    		+ "      AND (otc.status = 'PENDING' OR otc.status IS NULL OR otc.empcode IS NULL)\r\n"
//		    		+ ") final\r\n"
//		    		+ "WHERE final.otamount > 0\r\n"
//		    		+ "ORDER BY checkindate, empcode;\r\n"
//		    		+ ""
//		    		+ "",
//		    nativeQuery = true
//		)
//		List<Object[]> getFinalOtRecords(Long orgId);
	
	
	
	@Query(
		    value = "WITH company_cte AS (\r\n"
		    		+ "    SELECT * FROM company WHERE companyid = ?1 \r\n"
		    		+ "),\r\n"
		    		+ "shift_cte AS (\r\n"
		    		+ "    SELECT sd.employeecode,\r\n"
		    		+ "           sd.shifttype,\r\n"
		    		+ "           CASE \r\n"
		    		+ "               WHEN sd.outtime < sd.intime \r\n"
		    		+ "                    THEN TIME_TO_SEC(TIMEDIFF(ADDTIME(sd.outtime, '24:00:00'), sd.intime))\r\n"
		    		+ "               ELSE TIME_TO_SEC(TIMEDIFF(sd.outtime, sd.intime)) \r\n"
		    		+ "           END AS working_sec,\r\n"
		    		+ "           sd.effectivefrom, sd.effectiveto\r\n"
		    		+ "    FROM shiftassigndetails sd\r\n"
		    		+ "    JOIN shiftassign sa ON sd.shiftassignid = sa.shiftassignid\r\n"
		    		+ "    WHERE sa.orgid = ?1 AND sd.active = 1\r\n"
		    		+ "),\r\n"
		    		+ "salary_cte AS (\r\n"
		    		+ "    SELECT employeecode, sumofearning\r\n"
		    		+ "    FROM (\r\n"
		    		+ "        SELECT ss.employeecode, ss.sumofearning,\r\n"
		    		+ "               ROW_NUMBER() OVER (\r\n"
		    		+ "                   PARTITION BY ss.employeecode \r\n"
		    		+ "                   ORDER BY STR_TO_DATE(ss.createdon, '%d-%m-%Y %h:%i:%s %p') DESC\r\n"
		    		+ "               ) AS rn\r\n"
		    		+ "        FROM salarystructure ss \r\n"
		    		+ "        WHERE ss.orgid = ?1 AND ss.active = 1\r\n"
		    		+ "    ) t \r\n"
		    		+ "    WHERE t.rn = 1\r\n"
		    		+ "),\r\n"
		    		+ "otherpayments_cte AS (\r\n"
		    		+ "    SELECT employeecode, amount\r\n"
		    		+ "    FROM (\r\n"
		    		+ "        SELECT op.employeecode, op.amount,\r\n"
		    		+ "               ROW_NUMBER() OVER (\r\n"
		    		+ "                   PARTITION BY op.employeecode\r\n"
		    		+ "                   ORDER BY STR_TO_DATE(op.createdon, '%d-%m-%Y %h:%i:%s %p') DESC\r\n"
		    		+ "               ) AS rn\r\n"
		    		+ "        FROM otherpayments op\r\n"
		    		+ "        WHERE op.orgid = ?1 \r\n"
		    		+ "    ) t\r\n"
		    		+ "    WHERE t.rn = 1\r\n"
		    		+ "),\r\n"
		    		+ "attendance_cte AS (\r\n"
		    		+ "    SELECT ad.empcode, ad.empname, ad.branch, ad.branchcode, ad.checkindate,\r\n"
		    		+ "           ad.intime, ad.outtime, ad.effectivehours AS work_hrs\r\n"
		    		+ "    FROM attendancedaily ad\r\n"
		    		+ "    JOIN company_cte c ON ad.orgid = c.companyid\r\n"
		    		+ "    JOIN employee e ON ad.empcode = e.employeecode\r\n"
		    		+ "    WHERE ad.orgid = ?1 \r\n"
		    		+ "      AND FIND_IN_SET(ad.attendancemode, c.attendancemode)\r\n"
		    		+ "      AND c.otflag = 1\r\n"
		    		+ "      AND e.otflag = 1\r\n"
		    		+ "      AND (c.ottype = 'ALL' \r\n"
		    		+ "           OR (c.ottype = 'EMPLOYEE' AND LOWER(e.type) = 'employee') \r\n"
		    		+ "           OR (c.ottype = 'CONTRACTOR' AND LOWER(e.type) = 'contractor'))\r\n"
		    		+ "         AND ad.checkindate BETWEEN \r\n"
		    		+ "    DATE_FORMAT(CURRENT_DATE - INTERVAL 1 MONTH, '%Y-%m-01')\r\n"
		    		+ "    AND LAST_DAY(CURRENT_DATE)\r\n"
		    		+ "\r\n"
		    		+ "),\r\n"
		    		+ "daytype_cte AS (\r\n"
		    		+ "    SELECT ds.empcode, ds.checkindate,\r\n"
		    		+ "           CASE \r\n"
		    		+ "               WHEN h.holidaydate IS NOT NULL THEN 'Holiday'\r\n"
		    		+ "               WHEN EXISTS (\r\n"
		    		+ "                    SELECT 1 FROM companyweekoff cw \r\n"
		    		+ "                    WHERE cw.companyid = ?1 \r\n"
		    		+ "                      AND UPPER(cw.weekoffdays) = UPPER(DAYNAME(ds.checkindate))\r\n"
		    		+ "               ) THEN 'Weekly-Off'\r\n"
		    		+ "               ELSE 'Regular' \r\n"
		    		+ "           END AS daytype\r\n"
		    		+ "    FROM attendance_cte ds\r\n"
		    		+ "    LEFT JOIN holidays h ON h.orgid = ?1 AND h.holidaydate = ds.checkindate\r\n"
		    		+ "),\r\n"
		    		+ "ot_policy_cte AS (\r\n"
		    		+ "    SELECT om.otmasterid, om.otcategory, om.ottype, \r\n"
		    		+ "           omd.minhours * 3600 AS min_sec,\r\n"
		    		+ "           omd.maxhours * 3600 AS max_sec, \r\n"
		    		+ "           omd.otrate, omd.slab, \r\n"
		    		+ "           omd.effectivefrom, omd.effectiveto\r\n"
		    		+ "    FROM otmaster om\r\n"
		    		+ "    JOIN otmasterdetails omd ON omd.otmasterid = om.otmasterid\r\n"
		    		+ "    WHERE om.orgid = ?1 \r\n"
		    		+ "      AND om.active = 1 \r\n"
		    		+ "      AND omd.applicable = 1\r\n"
		    		+ "      AND UPPER(om.ottype) = 'SLAB'\r\n"
		    		+ "),\r\n"
		    		+ "combined_cte AS (\r\n"
		    		+ "    SELECT a.empcode, a.empname, a.branch, a.branchcode, a.checkindate,\r\n"
		    		+ "           STR_TO_DATE(a.intime, '%H:%i:%s') AS intime,\r\n"
		    		+ "           STR_TO_DATE(a.outtime, '%H:%i:%s') AS outtime,\r\n"
		    		+ "           a.work_hrs * 3600 AS work_sec,\r\n"
		    		+ "           COALESCE(sft.working_sec, 0) AS working_sec,\r\n"
		    		+ "           sft.shifttype,\r\n"
		    		+ "           d.daytype\r\n"
		    		+ "    FROM attendance_cte a\r\n"
		    		+ "    LEFT JOIN shift_cte sft \r\n"
		    		+ "           ON sft.employeecode = a.empcode \r\n"
		    		+ "          AND a.checkindate BETWEEN sft.effectivefrom AND sft.effectiveto\r\n"
		    		+ "    JOIN daytype_cte d \r\n"
		    		+ "           ON d.empcode = a.empcode \r\n"
		    		+ "          AND d.checkindate = a.checkindate\r\n"
		    		+ "),\r\n"
		    		+ "ot_calc_cte AS (\r\n"
		    		+ "    SELECT c.*, \r\n"
		    		+ "           COALESCE(c.work_sec - COALESCE(c.working_sec, 0), 0) AS raw_ot_sec\r\n"
		    		+ "    FROM combined_cte c\r\n"
		    		+ "),\r\n"
		    		+ "company_ot_policy AS (\r\n"
		    		+ "    SELECT companyid, otpolicy, oteligiblehours, shifthours \r\n"
		    		+ "    FROM company \r\n"
		    		+ "    WHERE companyid = ?1 \r\n"
		    		+ ")\r\n"
		    		+ "SELECT *\r\n"
		    		+ "FROM (\r\n"
		    		+ "    SELECT fr.empcode, fr.empname, fr.checkindate,\r\n"
		    		+ "           TIME_FORMAT(fr.intime, '%H:%i:%s') AS intime,\r\n"
		    		+ "           TIME_FORMAT(fr.outtime, '%H:%i:%s') AS outtime,\r\n"
		    		+ "\r\n"
		    		+ "           CAST(\r\n"
		    		+ "               CASE\r\n"
		    		+ "                   WHEN (UPPER(cp.otpolicy) = 'OTHERS' AND fr.shifttype = 'OPEN')\r\n"
		    		+ "                        THEN GREATEST(0, FLOOR(fr.work_sec / 3600) - cp.shifthours)\r\n"
		    		+ "                   ELSE FLOOR(fr.raw_ot_sec / 3600)\r\n"
		    		+ "               END AS SIGNED\r\n"
		    		+ "           ) AS othours,\r\n"
		    		+ "\r\n"
		    		+ "           -- Bank OT Amount\r\n"
		    		+ "           CASE\r\n"
		    		+ "               WHEN e.category IN (0,1) THEN \r\n"
		    		+ "                   CASE\r\n"
		    		+ "                       WHEN (UPPER(cp.otpolicy) = 'HOURLY' AND fr.shifttype <> 'OPEN') THEN \r\n"
		    		+ "                            ROUND((fr.raw_ot_sec / 3600) * (s.sumofearning / DAY(LAST_DAY(fr.checkindate)) / (fr.working_sec / 3600)), 2)\r\n"
		    		+ "                       WHEN (UPPER(cp.otpolicy) = 'SLAB' AND fr.shifttype <> 'OPEN' AND op.otrate IS NOT NULL) THEN\r\n"
		    		+ "                            ROUND((s.sumofearning / DAY(LAST_DAY(fr.checkindate))) * (op.otrate / 100), 2)\r\n"
		    		+ "                       WHEN (UPPER(cp.otpolicy) = 'OTHERS' AND fr.shifttype = 'OPEN'\r\n"
		    		+ "                             AND (fr.work_sec / 3600) >= (cp.shifthours + cp.oteligiblehours)) THEN \r\n"
		    		+ "                            ROUND(s.sumofearning / DAY(LAST_DAY(fr.checkindate)), 2)\r\n"
		    		+ "                       ELSE 0\r\n"
		    		+ "                   END\r\n"
		    		+ "               ELSE 0\r\n"
		    		+ "           END AS bankOtAmount,\r\n"
		    		+ "\r\n"
		    		+ "           -- Cash OT Amount\r\n"
		    		+ "           CASE\r\n"
		    		+ "               WHEN e.category = 1 THEN \r\n"
		    		+ "                   CASE\r\n"
		    		+ "                       WHEN (UPPER(cp.otpolicy) = 'HOURLY' AND fr.shifttype <> 'OPEN') THEN \r\n"
		    		+ "                            ROUND((fr.raw_ot_sec / 3600) * (opay.amount / DAY(LAST_DAY(fr.checkindate)) / (fr.working_sec / 3600)), 2)\r\n"
		    		+ "                       WHEN (UPPER(cp.otpolicy) = 'SLAB' AND fr.shifttype <> 'OPEN' AND op.otrate IS NOT NULL) THEN\r\n"
		    		+ "                            ROUND((opay.amount / DAY(LAST_DAY(fr.checkindate))) * (op.otrate / 100), 2)\r\n"
		    		+ "                       WHEN (UPPER(cp.otpolicy) = 'OTHERS' AND fr.shifttype = 'OPEN'\r\n"
		    		+ "                             AND (fr.work_sec / 3600) >= (cp.shifthours + cp.oteligiblehours)) THEN \r\n"
		    		+ "                            ROUND(opay.amount / DAY(LAST_DAY(fr.checkindate)), 2)\r\n"
		    		+ "                       ELSE 0\r\n"
		    		+ "                   END\r\n"
		    		+ "               ELSE 0\r\n"
		    		+ "           END AS cashOtAmount,\r\n"
		    		+ "\r\n"
		    		+ "           CASE \r\n"
		    		+ "               WHEN cp.otpolicy = 'SLAB' THEN COALESCE(op.otrate, 0) \r\n"
		    		+ "               ELSE 0 \r\n"
		    		+ "           END AS rate,\r\n"
		    		+ "\r\n"
		    		+ "           cp.otpolicy AS ottype,\r\n"
		    		+ "           CASE \r\n"
		    		+ "               WHEN UPPER(cp.otpolicy) = 'SLAB' THEN UPPER(op.otcategory) \r\n"
		    		+ "               WHEN UPPER(cp.otpolicy) = 'HOURLY' THEN 'HOURLY'\r\n"
		    		+ "               ELSE 'OTHERS' \r\n"
		    		+ "           END AS otcategory,\r\n"
		    		+ "           cp.otpolicy AS companyotpolicy,\r\n"
		    		+ "           otc.status AS otstatus\r\n"
		    		+ "\r\n"
		    		+ "    FROM ot_calc_cte fr\r\n"
		    		+ "    JOIN company_ot_policy cp ON cp.companyid = ?1 \r\n"
		    		+ "    JOIN salary_cte s ON s.employeecode = fr.empcode\r\n"
		    		+ "    LEFT JOIN otherpayments_cte opay ON opay.employeecode = fr.empcode\r\n"
		    		+ "    LEFT JOIN ot_policy_cte op \r\n"
		    		+ "           ON op.otcategory = fr.daytype\r\n"
		    		+ "          AND fr.raw_ot_sec BETWEEN op.min_sec AND op.max_sec\r\n"
		    		+ "          AND fr.checkindate BETWEEN op.effectivefrom AND op.effectiveto\r\n"
		    		+ "    LEFT JOIN otcalculation otc \r\n"
		    		+ "           ON otc.empcode = fr.empcode\r\n"
		    		+ "          AND otc.checkindate = fr.checkindate\r\n"
		    		+ "    JOIN employee e ON e.employeecode = fr.empcode\r\n"
		    		+ "\r\n"
		    		+ "    WHERE (\r\n"
		    		+ "            (UPPER(cp.otpolicy) = 'HOURLY' AND fr.shifttype <> 'OPEN' AND fr.raw_ot_sec > 0)\r\n"
		    		+ "         OR (UPPER(cp.otpolicy) = 'SLAB' AND fr.shifttype <> 'OPEN' AND op.otrate IS NOT NULL)\r\n"
		    		+ "         OR (UPPER(cp.otpolicy) = 'OTHERS' AND fr.shifttype = 'OPEN'\r\n"
		    		+ "             AND (fr.work_sec / 3600) >= (cp.shifthours + cp.oteligiblehours))\r\n"
		    		+ "    )\r\n"
		    		+ "      AND (otc.status = 'PENDING' OR otc.status IS NULL OR otc.empcode IS NULL)\r\n"
		    		+ ") final\r\n"
		    		+ "WHERE final.bankOtAmount + final.cashOtAmount > 0\r\n"
		    		+ "ORDER BY checkindate, empcode \r\n"
		    		+ ""
		    		+ "",
		    nativeQuery = true
		)
		List<Object[]> getFinalOtRecords(Long orgId);

	Optional<OtCalculationVO> findByEmpcodeAndCheckindate(String empcode, LocalDate checkindate);



	Optional<OtCalculationVO> findByEmpcodeAndCheckindateAndIntimeAndOuttime(String empcode, LocalDate checkindate,
			LocalTime intime, LocalTime outtime);


	@Query(nativeQuery = true, value = "SELECT a.*\r\n"
			+ "FROM otcalculation a\r\n"
			+ "JOIN employee e ON e.employeecode = a.empcode\r\n"
			+ "WHERE a.orgid = ?3\r\n"
			+ "  AND (UPPER(?4) = 'ALL' OR a.empcode = ?4)\r\n"
			+ "  AND (UPPER(?5) = 'ALL' OR UPPER(e.branch) = UPPER(?5))\r\n"
			+ "  AND (UPPER(?6) = 'ALL' OR UPPER(e.department) = UPPER(?6))\r\n"
			+ "  AND (\r\n"
			+ "       UPPER(?7) = 'ALL'\r\n"
			+ "       OR (UPPER(?7) = 'EMPLOYEE' AND e.type = 'EMPLOYEE')\r\n"
			+ "       OR (UPPER(?7) = 'CONTRACTOR' AND e.type = 'CONTRACTOR' AND UPPER(e.contractor) = UPPER(?8))\r\n"
			+ "  )\r\n"
			+ "  AND a.checkindate BETWEEN ?1 AND ?2\r\n"
			+ "  AND e.active = 1\r\n"
			+ "  AND a.status = 'PENDING' ORDER BY  a.empcode ASC\r\n"
			+ " \r\n"
			+ "")
	List<OtCalculationVO> getPendingOTHoursByOrgId(String fromDate, String toDate, Long orgId, String employeeCode,
			String branch, String department, String type, String contractor);


	@Query(nativeQuery = true, value = "SELECT a.*\r\n"
			+ "FROM otcalculation a\r\n"
			+ "JOIN employee e ON e.employeecode = a.empcode\r\n"
			+ "WHERE a.orgid = ?3\r\n"
			+ "  AND (UPPER(?4) = 'ALL' OR a.empcode = ?4)\r\n"
			+ "  AND (UPPER(?5) = 'ALL' OR UPPER(e.branch) = UPPER(?5))\r\n"
			+ "  AND (UPPER(?6) = 'ALL' OR UPPER(e.department) = UPPER(?6))\r\n"
			+ "  AND (\r\n"
			+ "       UPPER(?7) = 'ALL'\r\n"
			+ "       OR (UPPER(?7) = 'EMPLOYEE' AND e.type = 'EMPLOYEE')\r\n"
			+ "       OR (UPPER(?7) = 'CONTRACTOR' AND e.type = 'CONTRACTOR' AND UPPER(e.contractor) = UPPER(?8))\r\n"
			+ "  )\r\n"
			+ "  AND a.checkindate BETWEEN ?1 AND ?2\r\n"
			+ "  AND e.active = 1\r\n"
			+ "  AND a.status = 'APPROVED' \r\n"
			+ "")
	List<OtCalculationVO> getApprovedOTHoursByOrgId(String fromDate, String toDate, Long orgId, String employeeCode,
			String branch, String department, String type, String contractor);

}
