package com.efit.hrms.repo;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.springframework.data.annotation.QueryAnnotation;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.efit.hrms.entity.SalaryProcessVO;

@Repository
public interface SalaryProcessRepo extends JpaRepository<SalaryProcessVO, Long> {

	@Query(nativeQuery = true, value = "select * from salaryprocess a where a.orgid=?1 ")
	List<SalaryProcessVO> getAllSalaryProcessByOrgId(Long orgId);

	@Query(nativeQuery = true, value = "select * from salaryprocess a where a.salaryprocessid=?1 ")
	SalaryProcessVO getSalaryProcessById(Long id);

	@Query(nativeQuery = true, value = "SELECT \r\n"
			+ "    a.amount, \r\n"
			+ "    a.sumofearning, \r\n"
			+ "    a.sumofdetection, \r\n"
			+ "    COALESCE(SUM(ot.bankotamount), 0) AS totalotamount\r\n"
			+ "FROM salarystructure a\r\n"
			+ "LEFT JOIN otcalculation ot\r\n"
			+ "    ON a.employeecode = ot.empcode\r\n"
			+ "    AND ot.status = 'APPROVED'\r\n"
			+ "WHERE a.orgid = ?1\r\n"
			+ "  AND a.employeecode = ?2\r\n"
			+ "GROUP BY a.amount, a.sumofearning, a.sumofdetection, a.date\r\n"
			+ "ORDER BY a.date DESC\r\n"
			+ "LIMIT 1 \r\n"
			+ " ")
	Set<Object[]> getSalaryStructureForSalaryProcess(Long orgId, String employeeCode);

//	@Query(value = "            SELECT ROUND((?2 / ?1) * ?3) - ?4 AS netPay \r\n"
//			+ "", nativeQuery = true)
//	Set<Object[]> getNetPayForSalaryProcess( Long totalCompanyWorkingDays, BigDecimal grossPay,
//			Long empSalaryDays, BigDecimal sumOfDetection);

//	@Query(value = "SELECT ROUND(CAST(?1 AS DECIMAL) - CAST(?2 AS DECIMAL), 2) AS netPay", 
//		       nativeQuery = true)
//		Set<Object[]> getNetPayForSalaryProcess(BigDecimal grossPay, BigDecimal sumOfDetection);


	@Query(value = "	SELECT ROUND(\r\n"
			+ "    ((CAST(?2 AS DECIMAL(10,2)) - CAST(?4 AS DECIMAL(10,2))) \r\n"
			+ "     / CAST(?1 AS DECIMAL(10,2))) \r\n"
			+ "     * CAST(?3 AS DECIMAL(10,2)) \r\n"
			+ "     + CAST(?5 AS DECIMAL(10,2))\r\n"
			+ ") AS payOnHand "
			+ "", 
		       nativeQuery = true)
	Set<Object[]> getPayOnHandsForSalaryProcess(Long totalCompanyWorkingDays, BigDecimal grossPay, BigDecimal empSalaryDays,
			BigDecimal sumOfDetection, BigDecimal otAmount);

	

	@Query(nativeQuery = true, value = "SELECT * \r\n"
			+ "FROM salaryprocess a \r\n"
			+ "WHERE a.orgid = ?1 \r\n"
			+ " \r\n"
			+ "  AND (a.month = ?2 OR ?2 = 0) \r\n"
			+ "  AND (a.year = ?3 OR ?3 = 'ALL') AND a.approvedstatus = 'APPROVED' ")
	List<SalaryProcessVO> getApprovedSalaryProcessReport(Long orgId, Long month, String year);
	
	@Query(nativeQuery = true, value = "select distinct(a.employee),a.orgid,a.employeecode ,a.joiningdate, a.designation,a.department ,a.branch,a.branchcode,a.accountno,a.panno,a.uanno,empsalarydays as effectiveworkingdays,totalcompanyworkingdays as monthdays,a.bankname,s.lopleave,s.othours from employee a, salaryprocess s \r\n"
			+ "where a.employeecode =?2\r\n"
			+ " and a.employeecode = s.employeecode\r\n"
			+ "and a.orgid=?1 and s.month=?3 and s.year=?4 ")
	Set<Object[]> findpayslipemployeeandearningsdetails(Long orgId, String Employeecode, Long month, Long year );
	
//	@Query(nativeQuery = true, value = "SELECT \r\n"
//			+ "    employeename,\r\n"
//			+ "    orgid,\r\n"
//			+ "    employeecode,\r\n"
//			+ "    heading,\r\n"
//			+ "    amount,\r\n"
//			+ "    totalcompanyworkingdays,\r\n"
//			+ "    empsalarydays,\r\n"
//			+ "    actuals,\r\n"
//			+ "    payslipeffectivedate\r\n"
//			+ "FROM (\r\n"
//			+ "    -- Individual earnings\r\n"
//			+ "    SELECT \r\n"
//			+ "        b.employeename,\r\n"
//			+ "        b.orgid,\r\n"
//			+ "        b.employeecode,\r\n"
//			+ "        d.heading,\r\n"
//			+ "        d.amount,\r\n"
//			+ "        s.totalcompanyworkingdays,\r\n"
//			+ "        s.empsalarydays,\r\n"
//			+ "        ROUND((d.amount / s.totalcompanyworkingdays) * s.empsalarydays, 0) AS actuals,\r\n"
//			+ "        a.payslipeffectivedate\r\n"
//			+ "    FROM \r\n"
//			+ "        salarystructure b,\r\n"
//			+ "        employee a,\r\n"
//			+ "        salaryearningdetails d,\r\n"
//			+ "        salaryprocess s\r\n"
//			+ "    WHERE \r\n"
//			+ "        b.salarystructureid = d.salarystructureid\r\n"
//			+ "        AND b.employeecode = s.employeecode\r\n"
//			+ "        AND a.employeecode = b.employeecode\r\n"
//			+ "        AND b.active = 1\r\n"
//			+ "        AND b.employeecode = ?2\r\n"
//			+ "        AND b.orgid = ?1\r\n"
//			+ "        AND s.month = ?3\r\n"
//			+ "        AND s.year = ?4\r\n"
//			+ "        AND (?3 >= MONTH(a.payslipeffectivedate) OR YEAR(a.payslipeffectivedate) <= ?4)\r\n"
//			+ "    GROUP BY  \r\n"
//			+ "        b.employeename,\r\n"
//			+ "        b.orgid,\r\n"
//			+ "        b.employeecode,\r\n"
//			+ "        d.heading,\r\n"
//			+ "        d.amount,\r\n"
//			+ "        s.totalcompanyworkingdays,\r\n"
//			+ "        s.empsalarydays,\r\n"
//			+ "        a.payslipeffectivedate\r\n"
//			+ "\r\n"
//			+ "    UNION\r\n"
//			+ "\r\n"
//			+ "    -- Total earnings\r\n"
//			+ "    SELECT \r\n"
//			+ "        '' AS employeename,\r\n"
//			+ "        '' AS orgid,\r\n"
//			+ "        '' AS employeecode,\r\n"
//			+ "        'Total Earnings' AS heading,\r\n"
//			+ "        SUM(d.amount) AS amount,\r\n"
//			+ "        0 AS totalcompanyworkingdays,\r\n"
//			+ "        0 AS empsalarydays,\r\n"
//			+ "        SUM(ROUND((d.amount / s.totalcompanyworkingdays) * s.empsalarydays, 0)) AS actuals,\r\n"
//			+ "        a.payslipeffectivedate\r\n"
//			+ "    FROM \r\n"
//			+ "        salarystructure b,\r\n"
//			+ "        employee a,\r\n"
//			+ "        salaryearningdetails d,\r\n"
//			+ "        salaryprocess s\r\n"
//			+ "    WHERE \r\n"
//			+ "        b.salarystructureid = d.salarystructureid\r\n"
//			+ "        AND b.employeecode = s.employeecode\r\n"
//			+ "        AND a.employeecode = b.employeecode\r\n"
//			+ "        AND b.active = 1\r\n"
//			+ "        AND b.employeecode = ?2\r\n"
//			+ "        AND b.orgid = ?1\r\n"
//			+ "        AND s.month = ?3\r\n"
//			+ "        AND s.year = ?4\r\n"
//			+ "        AND (?3 >= MONTH(a.payslipeffectivedate) OR YEAR(a.payslipeffectivedate) <= ?4)\r\n"
//			+ "    GROUP BY \r\n"
//			+ "        a.payslipeffectivedate,\r\n"
//			+ "        s.totalcompanyworkingdays\r\n"
//			+ ") AS a\r\n"
//			+ "")
//	List<Object[]> findpayslipearningsdetails(Long orgId, String employeeCode, Long month, Long year);
	
	
	
	@Query(nativeQuery = true, value = " SELECT \r\n"
			+ "    employeename,\r\n"
			+ "    orgid,\r\n"
			+ "    employeecode,\r\n"
			+ "    heading,\r\n"
			+ "    amount,\r\n"
			+ "    totalcompanyworkingdays,\r\n"
			+ "    empsalarydays,\r\n"
			+ "    actuals,\r\n"
			+ "    payslipeffectivedate\r\n"
			+ "FROM (\r\n"
			+ "    -- Individual earnings from latest salarystructure\r\n"
			+ "    SELECT \r\n"
			+ "        b.employeename,\r\n"
			+ "        b.orgid,\r\n"
			+ "        b.employeecode,\r\n"
			+ "        d.heading,\r\n"
			+ "        d.amount,\r\n"
			+ "        s.totalcompanyworkingdays,\r\n"
			+ "        s.empsalarydays,\r\n"
			+ "        ROUND((d.amount / s.totalcompanyworkingdays) * s.empsalarydays, 0) AS actuals,\r\n"
			+ "        a.payslipeffectivedate\r\n"
			+ "    FROM (\r\n"
			+ "        SELECT * \r\n"
			+ "        FROM salarystructure \r\n"
			+ "        WHERE active = 1 AND employeecode = ?2 AND orgid = ?1\r\n"
			+ "        ORDER BY createdon DESC\r\n"
			+ "        LIMIT 1\r\n"
			+ "    ) b\r\n"
			+ "    JOIN employee a ON a.employeecode = b.employeecode\r\n"
			+ "    JOIN salaryearningdetails d ON b.salarystructureid = d.salarystructureid\r\n"
			+ "    JOIN salaryprocess s ON b.employeecode = s.employeecode\r\n"
			+ "    WHERE \r\n"
			+ "        s.month = ?3\r\n"
			+ "        AND s.year = ?4\r\n"
			+ "        AND (?3 >= MONTH(a.payslipeffectivedate) OR YEAR(a.payslipeffectivedate) <= ?4)\r\n"
			+ "    GROUP BY  \r\n"
			+ "        b.employeename,\r\n"
			+ "        b.orgid,\r\n"
			+ "        b.employeecode,\r\n"
			+ "        d.heading,\r\n"
			+ "        d.amount,\r\n"
			+ "        s.totalcompanyworkingdays,\r\n"
			+ "        s.empsalarydays,\r\n"
			+ "        a.payslipeffectivedate\r\n"
			+ "\r\n"
			+ "    UNION ALL\r\n"
			+ "\r\n"
			+ "    -- OT Amount as separate heading\r\n"
			+ "    SELECT\r\n"
			+ "        s.employeename,\r\n"
			+ "        s.orgid,\r\n"
			+ "        s.employeecode,\r\n"
			+ "        'Other Allowance' AS heading,\r\n"
			+ "        s.bankotamount AS amount,\r\n"
			+ "        s.totalcompanyworkingdays,\r\n"
			+ "        s.empsalarydays,\r\n"
			+ "        s.bankotamount AS actuals,\r\n"
			+ "        a.payslipeffectivedate\r\n"
			+ "    FROM \r\n"
			+ "        salaryprocess s\r\n"
			+ "    JOIN employee a ON a.employeecode = s.employeecode\r\n"
			+ "    WHERE \r\n"
			+ "        s.employeecode = ?2\r\n"
			+ "        AND s.orgid = ?1\r\n"
			+ "        AND s.month = ?3\r\n"
			+ "        AND s.year = ?4\r\n"
			+ "        AND s.bankotamount > 0 \r\n"
			+ "\r\n"
			+ "    UNION ALL\r\n"
			+ "\r\n"
			+ "    -- Total earnings (including OT)\r\n"
			+ "    SELECT \r\n"
			+ "        '' AS employeename,\r\n"
			+ "        '' AS orgid,\r\n"
			+ "        '' AS employeecode,\r\n"
			+ "        'Total Earnings' AS heading,\r\n"
			+ "        SUM(d.amount) + COALESCE(MAX(s.bankotamount),0) AS amount,\r\n"
			+ "        0 AS totalcompanyworkingdays,\r\n"
			+ "        0 AS empsalarydays,\r\n"
			+ "        SUM(ROUND((d.amount / s.totalcompanyworkingdays) * s.empsalarydays, 0)) + COALESCE(MAX(s.bankotamount),0) AS actuals,\r\n"
			+ "        a.payslipeffectivedate\r\n"
			+ "    FROM (\r\n"
			+ "        SELECT * \r\n"
			+ "        FROM salarystructure \r\n"
			+ "        WHERE active = 1 AND employeecode = ?2 AND orgid = ?1\r\n"
			+ "        ORDER BY createdon DESC\r\n"
			+ "        LIMIT 1\r\n"
			+ "    ) b\r\n"
			+ "    JOIN employee a ON a.employeecode = b.employeecode\r\n"
			+ "    JOIN salaryearningdetails d ON b.salarystructureid = d.salarystructureid\r\n"
			+ "    JOIN salaryprocess s ON b.employeecode = s.employeecode\r\n"
			+ "    WHERE \r\n"
			+ "        s.month = ?3\r\n"
			+ "        AND s.year = ?4\r\n"
			+ "        AND (?3 >= MONTH(a.payslipeffectivedate) OR YEAR(a.payslipeffectivedate) <= ?4)\r\n"
			+ "    GROUP BY \r\n"
			+ "        a.payslipeffectivedate,\r\n"
			+ "        s.totalcompanyworkingdays\r\n"
			+ ") AS a\r\n"
			+ "")
	List<Object[]> findpayslipearningsdetails(Long orgId, String employeeCode, Long month, Long year);

	@Query(value = "WITH latest_structure AS (\r\n"
			+ "    SELECT *\r\n"
			+ "    FROM salarystructure \r\n"
			+ "    WHERE active = 1\r\n"
			+ "      AND employeecode = ?2\r\n"
			+ "      AND orgid = ?1\r\n"
			+ "    ORDER BY STR_TO_DATE(createdon, '%d-%m-%Y %h:%i:%s %p') DESC, salarystructureid DESC\r\n"
			+ "    LIMIT 1\r\n"
			+ "),\r\n"
			+ "latest_advance AS (\r\n"
			+ "    SELECT COALESCE(bank, 0) AS bank_amount\r\n"
			+ "    FROM advanceupload\r\n"
			+ "    WHERE active = 1\r\n"
			+ "      AND employeecode = ?2\r\n"
			+ "      AND orgid = ?1\r\n"
			+ "      AND month = ?3\r\n"
			+ "      AND year = ?4\r\n"
			+ "    ORDER BY STR_TO_DATE(createdon, '%d-%m-%Y %h:%i:%s %p') DESC, advanceid DESC\r\n"
			+ "    LIMIT 1\r\n"
			+ ")\r\n"
			+ "SELECT \r\n"
			+ "    employee,\r\n"
			+ "    orgid,\r\n"
			+ "    employeecode,\r\n"
			+ "    heading,\r\n"
			+ "    amount\r\n"
			+ "FROM (\r\n"
			+ "    -- Individual deductions\r\n"
			+ "    SELECT \r\n"
			+ "        e.employee,\r\n"
			+ "        e.orgid,\r\n"
			+ "        e.employeecode,\r\n"
			+ "        sd.heading,\r\n"
			+ "        sd.amount\r\n"
			+ "    FROM latest_structure ls\r\n"
			+ "    JOIN employee e ON e.employeecode = ls.employeecode\r\n"
			+ "    JOIN salarydetectiondetails sd ON sd.salarystructureid = ls.salarystructureid\r\n"
			+ "    WHERE (YEAR(e.payslipeffectivedate) < ?4\r\n"
			+ "           OR (YEAR(e.payslipeffectivedate) = ?4 AND MONTH(e.payslipeffectivedate) <= ?3))\r\n"
			+ "\r\n"
			+ "    UNION ALL\r\n"
			+ "\r\n"
			+ "    -- Advance as a separate row\r\n"
			+ "    SELECT\r\n"
			+ "        '' AS employee,\r\n"
			+ "        '' AS orgid,\r\n"
			+ "        '' AS employeecode,\r\n"
			+ "        'Advance' AS heading,\r\n"
			+ "        la.bank_amount AS amount\r\n"
			+ "    FROM latest_advance la\r\n"
			+ "\r\n"
			+ "    UNION ALL\r\n"
			+ "\r\n"
			+ "    -- Total Deduction: salary deductions + advance\r\n"
			+ "    SELECT\r\n"
			+ "        '' AS employee,\r\n"
			+ "        '' AS orgid,\r\n"
			+ "        '' AS employeecode,\r\n"
			+ "        'Total Deduction' AS heading,\r\n"
			+ "        SUM(sd.amount) + COALESCE(MAX(la.bank_amount),0) AS amount\r\n"
			+ "    FROM latest_structure ls\r\n"
			+ "    JOIN salarydetectiondetails sd ON sd.salarystructureid = ls.salarystructureid\r\n"
			+ "    CROSS JOIN latest_advance la\r\n"
			+ ") AS a\r\n"
			+ "ORDER BY \r\n"
			+ "    CASE \r\n"
			+ "        WHEN heading='Total Deduction' THEN 3\r\n"
			+ "        WHEN heading='Advance' THEN 2\r\n"
			+ "        ELSE 0\r\n"
			+ "    END,\r\n"
			+ "    heading\r\n"
			+ " \r\n"
			+ "", nativeQuery = true)
	List<Object[]> findpayslipdeductionsdetails(Long orgId, String Employeecode , Long Month,Long year);
	
	@Query(nativeQuery = true, value ="        SELECT \r\n"
			+ "    employee,\r\n"
			+ "    orgid,\r\n"
			+ "    employeecode,\r\n"
			+ "    SUM(CASE \r\n"
			+ "            WHEN heading = 'Total Earnings' THEN total \r\n"
			+ "            ELSE -total \r\n"
			+ "        END) AS totalsum\r\n"
			+ "FROM (\r\n"
			+ "    SELECT \r\n"
			+ "        a.employee,\r\n"
			+ "        a.orgid,\r\n"
			+ "        a.employeecode,\r\n"
			+ "        'Total Earnings' AS heading,\r\n"
			+ "        SUM(ROUND((d.amount / s.emptotalworkingdays) * s.empsalarydays, 0)) AS total\r\n"
			+ "    FROM \r\n"
			+ "        salarystructure b\r\n"
			+ "        JOIN salaryearningdetails d ON b.salarystructureid = d.salarystructureid\r\n"
			+ "        JOIN salaryprocess s ON b.employeecode = s.employeecode\r\n"
			+ "        JOIN employee a ON a.employeecode = s.employeecode\r\n"
			+ "    WHERE \r\n"
			+ "        b.active = 1\r\n"
			+ "        AND b.employeecode = ?2\r\n"
			+ "        AND b.orgid = ?1\r\n"
			+ "        AND MONTH(a.payslipeffectivedate) >= ?3\r\n"
			+ "        AND s.month = ?3\r\n"
			+ "        AND s.year = ?4\r\n"
			+ "    GROUP BY \r\n"
			+ "        a.employee,\r\n"
			+ "        a.orgid,\r\n"
			+ "        a.employeecode\r\n"
			+ "    UNION \r\n"
			+ "    SELECT \r\n"
			+ "        a.employee,\r\n"
			+ "        a.orgid,\r\n"
			+ "        a.employeecode,\r\n"
			+ "        'Total Deduction' AS heading,\r\n"
			+ "        SUM(c.amount)\r\n"
			+ "    FROM \r\n"
			+ "        employee a\r\n"
			+ "        JOIN salarystructure b ON a.employeecode = b.employeecode\r\n"
			+ "        JOIN salarydetectiondetails c ON c.salarystructureid = b.salarystructureid\r\n"
			+ "    WHERE \r\n"
			+ "        b.active = 1\r\n"
			+ "        AND b.employeecode = ?2\r\n"
			+ "        AND b.orgid = ?1\r\n"
			+ "        AND ?3 >= MONTH(a.payslipeffectivedate)\r\n"
			+ "        AND ?4 >= YEAR(a.payslipeffectivedate)\r\n"
			+ "    GROUP BY \r\n"
			+ "        a.employee,\r\n"
			+ "        a.orgid,\r\n"
			+ "        a.employeecode\r\n"
			+ ") a\r\n"
			+ "GROUP BY \r\n"
			+ "    employee,\r\n"
			+ "    orgid,\r\n"
			+ "    employeecode")
			Set<Object[]> findpayslipshandsondetails(Long orgId, String employeecode, Long month, Long year);


			@Query(nativeQuery = true, value = "select companyid,companycode,companyname,address,city,state,zipcode,companylogo from company c \r\n"
					+ "where companyid =?1")
			Set<Object[]> findpayslipcompanydetails (Long orgId );

			@Query("SELECT s FROM SalaryProcessVO s WHERE s.orgId = ?1 AND s.employeeCode = ?2 AND s.month = ?3 AND s.year = ?4")
			List<SalaryProcessVO> findByOrgIdAndEmployeeCodeAndMonthAndYear(Long orgId, String employeeCode, Long month, String year);

			
			@Query(value = "SELECT s.bankamount " +
		               "FROM salaryprocess s " +
		               "WHERE s.orgid = ?1 AND s.employeecode = ?2 AND s.month = ?3 AND s.year = ?4",
		       nativeQuery = true)
		Set<BigDecimal> getpayslipPayOnHandAmount(Long orgId, String employeeCode, Long month, String year);

			
			@Query(nativeQuery = true, value = 
				    "SELECT * " +
				    "FROM salaryprocess a " +
				    "WHERE a.orgid = ?1 " +
				    "  AND (UPPER(?2) = 'ALL' OR UPPER(a.branch) = UPPER(?2)) " +
				    "AND a.approvedstatus = 'PENDING'"
				)
			List<SalaryProcessVO> getPendingSalaryProcessByOrgId(Long orgId, String branch);

			
			
//			@Query(nativeQuery = true, value = 
//				    "SELECT\r\n"
//				    + "    -- Total earnings including OT\r\n"
//				    + "    ROUND(\r\n"
//				    + "        COALESCE(s.sumofearning, 0) + COALESCE(ot.bankotamount, 0) \r\n"
//				    + "    ) AS sumOfEarnings,\r\n"
//				    + "\r\n"
//				    + "    -- Total deductions (example calculation)\r\n"
//				    + "    ROUND(\r\n"
//				    + "         COALESCE(s.sumofearning - ((s.sumofearning / ?1 ) * ?2 ), 0) + s.sumofdetection\r\n"
//				    + "    ) AS sumOfDeduction,\r\n"
//				    + "\r\n"
//				    + "    -- Bank amount after OT and advances\r\n"
//				    + "    ROUND(\r\n"
//				    + "        COALESCE((s.sumofearning / ?1 ) * ?2 - s.sumofdetection, 0) \r\n"
//				    + "        + COALESCE(ot.bankotamount, 0) \r\n"
//				    + "        - COALESCE(ad.bank, 0)\r\n"
//				    + "    ) AS bankAmount,\r\n"
//				    + "\r\n"
//				    + "    -- Cash amount after OT and advances\r\n"
//				    + "    ROUND(\r\n"
//				    + "        COALESCE(\r\n"
//				    + "            CASE \r\n"
//				    + "                WHEN e.category = 0 THEN 0 \r\n"
//				    + "                ELSE (op.amount / ?1 ) * ?2\r\n"
//				    + "            END, 0\r\n"
//				    + "        )\r\n"
//				    + "        + COALESCE(ot.cashotamount, 0)\r\n"
//				    + "        - COALESCE(ad.cash, 0)\r\n"
//				    + "    ) AS cashAmount,\r\n"
//				    + "\r\n"
//				    + "    -- OT details separately\r\n"
//				    + "    COALESCE(ot.bankotamount, 0) AS bankOtAmount,\r\n"
//				    + "    COALESCE(ot.cashotamount, 0) AS cashOtAmount,\r\n"
//				    + "\r\n"
//				    + "    -- Advance details separately\r\n"
//				    + "    COALESCE(ad.bank, 0) AS bankAdvance,\r\n"
//				    + "    COALESCE(ad.cash, 0) AS cashAdvance\r\n"
//				    + "\r\n"
//				    + "FROM employee e\r\n"
//				    + "\r\n"
//				    + "-- Join with latest salary structure per employee\r\n"
//				    + "JOIN (\r\n"
//				    + "    SELECT ss.*\r\n"
//				    + "    FROM salarystructure ss\r\n"
//				    + "    WHERE STR_TO_DATE(ss.createdon, '%d-%m-%Y %h:%i:%s %p') = (\r\n"
//				    + "        SELECT MAX(STR_TO_DATE(s2.createdon, '%d-%m-%Y %h:%i:%s %p'))\r\n"
//				    + "        FROM salarystructure s2\r\n"
//				    + "        WHERE s2.employeeCode = ss.employeeCode\r\n"
//				    + "          AND s2.orgId = ss.orgId\r\n"
//				    + "    )\r\n"
//				    + ") s ON s.employeeCode = e.employeeCode AND s.orgId = e.orgId\r\n"
//				    + "\r\n"
//				    + "-- Join with latest other payments per employee\r\n"
//				    + "LEFT JOIN (\r\n"
//				    + "    SELECT op1.*\r\n"
//				    + "    FROM otherpayments op1\r\n"
//				    + "    WHERE STR_TO_DATE(op1.createdon, '%d-%m-%Y %h:%i:%s %p') = (\r\n"
//				    + "        SELECT MAX(STR_TO_DATE(op2.createdon, '%d-%m-%Y %h:%i:%s %p'))\r\n"
//				    + "        FROM otherpayments op2\r\n"
//				    + "        WHERE op2.employeeCode = op1.employeeCode\r\n"
//				    + "          AND op2.orgId = op1.orgId\r\n"
//				    + "    )\r\n"
//				    + ") op ON op.employeeCode = e.employeeCode AND op.orgId = e.orgId\r\n"
//				    + "\r\n"
//				    + "-- Join OT calculation for the given month/year\r\n"
//				    + "LEFT JOIN (\r\n"
//				    + "    SELECT oc.empcode, \r\n"
//				    + "           SUM(oc.bankotamount) AS bankotamount,\r\n"
//				    + "           SUM(oc.cashotamount) AS cashotamount\r\n"
//				    + "    FROM otcalculation oc\r\n"
//				    + "    WHERE oc.status = 'PENDING'\r\n"
//				    + "      AND YEAR(oc.checkindate) = ?7\r\n"
//				    + "      AND MONTH(oc.checkindate) = ?6\r\n"
//				    + "    GROUP BY oc.empcode\r\n"
//				    + ") ot ON ot.empcode = e.employeeCode\r\n"
//				    + "\r\n"
//				    + "-- Join advances for the given month/year\r\n"
//				    + "LEFT JOIN (\r\n"
//				    + "    SELECT a.employeecode,\r\n"
//				    + "           SUM(a.bank) AS bank,\r\n"
//				    + "           SUM(a.cash) AS cash\r\n"
//				    + "    FROM advanceupload a\r\n"
//				    + "    WHERE a.active = 1\r\n"
//				    + "      AND a.year = ?7\r\n"
//				    + "      AND a.month = ?6\r\n"
//				    + "    GROUP BY a.employeecode\r\n"
//				    + ") ad ON ad.employeecode = e.employeeCode\r\n"
//				    + "\r\n"
//				    + "WHERE e.employeeCode = ?4\r\n"
//				    + "  AND e.orgId = ?3\r\n"
//				    + "  AND e.branchcode = ?5\r\n"
//				)
//			List<Object[]> getBankAndCashAmtForSalaryProcess(Long totalCompanyWorkingDays, BigDecimal empSalaryDays,
//					Long orgId, String employeeCode, String branchCode, Long month, Long year);


			@Query(nativeQuery = true, value = 
				    "SELECT\r\n"
				    + "    -- Total earnings including OT\r\n"
				    + "    GREATEST(\r\n"
				    + "        ROUND(\r\n"
				    + "            COALESCE(s.sumofearning, 0) + COALESCE(ot.bankotamount, 0)\r\n"
				    + "        ), 0\r\n"
				    + "    ) AS sumOfEarnings,\r\n"
				    + "\r\n"
				    + "    -- Total deductions (example calculation)\r\n"
				    + "    GREATEST(\r\n"
				    + "        ROUND(\r\n"
				    + "            COALESCE(s.sumofearning - ((s.sumofearning / ?1 ) * ?2 ), 0) + s.sumofdetection\r\n"
				    + "        ), 0\r\n"
				    + "    ) AS sumOfDeduction,\r\n"
				    + "\r\n"
				    + "    -- Bank amount after OT and advances\r\n"
				    + "    GREATEST(\r\n"
				    + "        ROUND(\r\n"
				    + "            COALESCE((s.sumofearning / ?1 ) * ?2 - s.sumofdetection, 0) \r\n"
				    + "            + COALESCE(ot.bankotamount, 0) \r\n"
				    + "            - COALESCE(ad.bank, 0)\r\n"
				    + "        ), 0\r\n"
				    + "    ) AS bankAmount,\r\n"
				    + "\r\n"
				    + "    -- Cash amount after OT and advances\r\n"
				    + "    GREATEST(\r\n"
				    + "        ROUND(\r\n"
				    + "            COALESCE(\r\n"
				    + "                CASE \r\n"
				    + "                    WHEN e.category = 0 THEN 0 \r\n"
				    + "                    ELSE (op.amount / ?1 ) * ?2\r\n"
				    + "                END, 0\r\n"
				    + "            )\r\n"
				    + "            + COALESCE(ot.cashotamount, 0)\r\n"
				    + "            - COALESCE(ad.cash, 0)\r\n"
				    + "        ), 0\r\n"
				    + "    ) AS cashAmount,\r\n"
				    + "\r\n"
				    + "    -- OT details separately\r\n"
				    + "    GREATEST(COALESCE(ot.bankotamount, 0), 0) AS bankOtAmount,\r\n"
				    + "    GREATEST(COALESCE(ot.cashotamount, 0), 0) AS cashOtAmount,\r\n"
				    + "\r\n"
				    + "    -- Advance details separately\r\n"
				    + "    GREATEST(COALESCE(ad.bank, 0), 0) AS bankAdvance,\r\n"
				    + "    GREATEST(COALESCE(ad.cash, 0), 0) AS cashAdvance,\r\n"
				    + "\r\n"
				    + "    -- PF and ESI separately (only extra fields)\r\n"
				    + "    GREATEST(COALESCE(sd.pf, 0), 0) AS pfAmount,\r\n"
				    + "    GREATEST(COALESCE(sd.esi, 0), 0) AS esiAmount\r\n"
				    + "\r\n"
				    + "FROM employee e\r\n"
				    + "\r\n"
				    + "-- Join with latest salary structure per employee\r\n"
				    + "JOIN (\r\n"
				    + "    SELECT ss.*\r\n"
				    + "    FROM salarystructure ss\r\n"
				    + "    WHERE STR_TO_DATE(ss.createdon, '%d-%m-%Y %h:%i:%s %p') = (\r\n"
				    + "        SELECT MAX(STR_TO_DATE(s2.createdon, '%d-%m-%Y %h:%i:%s %p'))\r\n"
				    + "        FROM salarystructure s2\r\n"
				    + "        WHERE s2.employeeCode = ss.employeeCode\r\n"
				    + "          AND s2.orgId = ss.orgId\r\n"
				    + "    )\r\n"
				    + ") s ON s.employeeCode = e.employeeCode AND s.orgId = e.orgId\r\n"
				    + "\r\n"
				    + "-- Join PF and ESI from salarydeductiondetails\r\n"
				    + "LEFT JOIN (\r\n"
				    + "    SELECT sd.salarystructureid,\r\n"
				    + "           SUM(CASE WHEN sd.heading = 'Provident Fund' THEN sd.amount ELSE 0 END) AS pf,\r\n"
				    + "           SUM(CASE WHEN sd.heading = 'Employee State Insurance' THEN sd.amount ELSE 0 END) AS esi\r\n"
				    + "    FROM salarydetectiondetails sd\r\n"
				    + "    WHERE sd.salarystructureid IN (\r\n"
				    + "        SELECT ss.salarystructureid\r\n"
				    + "        FROM salarystructure ss\r\n"
				    + "        WHERE STR_TO_DATE(ss.createdon, '%d-%m-%Y %h:%i:%s %p') = (\r\n"
				    + "            SELECT MAX(STR_TO_DATE(s2.createdon, '%d-%m-%Y %h:%i:%s %p'))\r\n"
				    + "            FROM salarystructure s2\r\n"
				    + "            WHERE s2.employeeCode = ss.employeeCode\r\n"
				    + "              AND s2.orgId = ss.orgId\r\n"
				    + "        )\r\n"
				    + "    )\r\n"
				    + "    GROUP BY sd.salarystructureid\r\n"
				    + ") sd ON sd.salarystructureid = s.salarystructureid\r\n"
				    + "\r\n"
				    + "-- Join with latest other payments per employee\r\n"
				    + "LEFT JOIN (\r\n"
				    + "    SELECT op1.*\r\n"
				    + "    FROM otherpayments op1\r\n"
				    + "    WHERE STR_TO_DATE(op1.createdon, '%d-%m-%Y %h:%i:%s %p') = (\r\n"
				    + "        SELECT MAX(STR_TO_DATE(op2.createdon, '%d-%m-%Y %h:%i:%s %p'))\r\n"
				    + "        FROM otherpayments op2\r\n"
				    + "        WHERE op2.employeeCode = op1.employeeCode\r\n"
				    + "          AND op2.orgId = op1.orgId\r\n"
				    + "    )\r\n"
				    + ") op ON op.employeeCode = e.employeeCode AND op.orgId = e.orgId\r\n"
				    + "\r\n"
				    + "-- Join OT calculation for the given month/year\r\n"
				    + "LEFT JOIN (\r\n"
				    + "    SELECT oc.empcode, \r\n"
				    + "           SUM(oc.bankotamount) AS bankotamount,\r\n"
				    + "           SUM(oc.cashotamount) AS cashotamount\r\n"
				    + "    FROM otcalculation oc\r\n"
				    + "    WHERE oc.status = 'PENDING'\r\n"
				    + "      AND YEAR(oc.checkindate) = ?7\r\n"
				    + "      AND MONTH(oc.checkindate) = ?6\r\n"
				    + "    GROUP BY oc.empcode\r\n"
				    + ") ot ON ot.empcode = e.employeeCode\r\n"
				    + "\r\n"
				    + "-- Join advances for the given month/year\r\n"
				    + "LEFT JOIN (\r\n"
				    + "    SELECT a.employeecode,\r\n"
				    + "           SUM(a.bank) AS bank,\r\n"
				    + "           SUM(a.cash) AS cash\r\n"
				    + "    FROM advanceupload a\r\n"
				    + "    WHERE a.active = 1\r\n"
				    + "      AND a.year = ?7\r\n"
				    + "      AND a.month = ?6\r\n"
				    + "    GROUP BY a.employeecode\r\n"
				    + ") ad ON ad.employeecode = e.employeeCode\r\n"
				    + "\r\n"
				    + "WHERE e.employeeCode = ?4\r\n"
				    + "  AND e.orgId = ?3\r\n"
				    + "  AND e.branchcode = ?5 \r\n"
				    + " \r\n"
				    + " \r\n"
				    + "\r\n"
				)
			List<Object[]> getBankAndCashAmtForSalaryProcess(Long totalCompanyWorkingDays, BigDecimal empSalaryDays,
					Long orgId, String employeeCode, String branchCode, Long month, Long year);
			
			
			
			@Query(nativeQuery = true, value = "select finyear,month as month from attendancesummary where (orgid,finyear,month,empcode,empname) not in(select orgid,year,month,employeecode,employeename from salaryprocess group by orgid,year,month,employeecode,employeename) and orgid=?1 group by finyear,month order by finyear,month asc")
				Set<Object[]>getYearAndMonth(Long orgId);



}
